import { useState, useCallback, useMemo, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { differenceInDays, parseISO, format, addDays } from 'date-fns';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';

import {
  Sparkles,
  Wand2,
  ChevronRight,
  ChevronLeft,
  Check,
  Loader2,
  Target,
  Mic,
  Calendar,
  Zap,
  Flag,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { useEpicSuggestions, type EpicSuggestion, type ClarificationAnswers } from '@/hooks/useEpicSuggestions';
import { useEpicTemplates, EpicTemplate } from '@/hooks/useEpicTemplates';
import { useUserAIContext } from '@/hooks/useUserAIContext';
import { useAIInteractionTracker } from '@/hooks/useAIInteractionTracker';
import { useHapticFeedback } from '@/hooks/useHapticFeedback';
import { useJourneySchedule, type JourneyRitual } from '@/hooks/useJourneySchedule';
import { useIntentClassifier } from '@/hooks/useIntentClassifier';
import { SuggestionCard } from './SuggestionCard';
import { RitualEditor } from './RitualEditor';
import { PostcardPreview } from './PostcardPreview';
import { CapacityWarningBanner } from '@/components/CapacityWarningBanner';
import { themeColors } from './StoryStep';
import { EpicClarificationFlow } from '@/features/tasks/components/EpicClarificationFlow';
import { storyTypes } from '@/components/narrative/StoryTypeSelector';
import { DeadlinePicker } from '@/components/JourneyWizard/DeadlinePicker';
import { TimelineView } from '@/components/JourneyWizard/TimelineView';
import { AdjustmentInput } from '@/components/JourneyWizard/AdjustmentInput';
import { useVoiceInput } from '@/hooks/useVoiceInput';
import { EPIC_XP_REWARDS } from '@/config/xpRewards';
import type { StoryTypeSlug } from '@/types/narrativeTypes';

type WizardStep = 'goal' | 'timeline' | 'suggestions' | 'review';

interface PathfinderProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onCreateEpic: (data: {
    title: string;
    description?: string;
    target_days: number;
    habits: Array<{
      title: string;
      description?: string;
      difficulty: string;
      frequency: string;
      custom_days: number[];
      estimated_minutes?: number;
    }>;
    milestones?: Array<{
      title: string;
      description?: string;
      target_date: string;
      milestone_percent: number;
      is_postcard_milestone: boolean;
    }>;
    phases?: Array<{
      name: string;
      description: string;
      start_date: string;
      end_date: string;
      phase_order: number;
    }>;
    is_public?: boolean;
    story_type_slug?: StoryTypeSlug;
    theme_color?: string;
  }) => void;
  isCreating: boolean;
  initialGoal?: string;
  initialTargetDays?: number;
  template?: EpicTemplate | null;
  showTemplatesFirst?: boolean;
  clarificationAnswers?: ClarificationAnswers;
  epicContext?: string;
}

export function Pathfinder({
  open,
  onOpenChange,
  onCreateEpic,
  isCreating,
  initialGoal = '',
  initialTargetDays,
  template,
  showTemplatesFirst = false,
  clarificationAnswers,
  epicContext,
}: PathfinderProps) {
  const hasAutoGeneratedRef = useRef(false);
  const scrollContainerRef = useRef<HTMLDivElement>(null);
  const [step, setStep] = useState<WizardStep>('goal');
  const [goalInput, setGoalInput] = useState(initialGoal);
  const [deadline, setDeadline] = useState<Date | undefined>(undefined);
  
  // Timeline context state
  const [timelineContext, setTimelineContext] = useState('');
  
  const { preferences, isAtEpicLimit } = useUserAIContext();
  const { trackInteraction } = useAIInteractionTracker();
  const { schedule, isLoading: isScheduleLoading, generateSchedule, adjustSchedule, toggleMilestone, updateMilestoneDate, reset: resetSchedule, setRituals, postcardCount, maxPostcards } = useJourneySchedule();
  const [originalRituals, setOriginalRituals] = useState<JourneyRitual[]>([]);
  
  // AI Clarification state
  const {
    classify,
    isClassifying,
    classification,
    clarifyEpic,
    reset: resetClassification,
  } = useIntentClassifier({ useOrchestrator: false });
  const [showClarification, setShowClarification] = useState(false);
  const [localClarificationAnswers, setLocalClarificationAnswers] = useState<Record<string, string | number>>({});
  const [localEpicContext, setLocalEpicContext] = useState<string | undefined>(undefined);
  
  const targetDays = useMemo(() => {
    if (deadline) {
      return Math.max(7, differenceInDays(deadline, new Date()));
    }
    if (initialTargetDays) return initialTargetDays;
    return preferences.epicDuration || 30;
  }, [deadline, initialTargetDays, preferences.epicDuration]);
  
  const [epicTitle, setEpicTitle] = useState('');
  const [epicWhy, setEpicWhy] = useState('');
  const [customHabits, setCustomHabits] = useState<EpicSuggestion[]>([]);
  const [storyType, setStoryType] = useState<StoryTypeSlug | null>(null);
  const [themeColor, setThemeColor] = useState(themeColors[0].id);
  const [selectedTemplate, setSelectedTemplate] = useState<EpicTemplate | null>(template || null);
  const { medium, success, light, tap } = useHapticFeedback();
  
  const { templates, incrementPopularity } = useEpicTemplates();
  const {
    suggestions,
    isLoading: isGenerating,
    error,
    generateSuggestions,
    toggleSuggestion,
    selectAll,
    deselectAll,
    getSelectedSuggestions,
    reset: resetSuggestions,
  } = useEpicSuggestions();

  const [interimText, setInterimText] = useState('');
  
  const {
    isRecording,
    isAutoStopping,
    startRecording,
    stopRecording,
  } = useVoiceInput({
    onInterimResult: (text) => setInterimText(text),
    onFinalResult: (text) => {
      setGoalInput((prev) => (prev ? prev + ' ' + text : text).trim());
      setInterimText('');
      success();
    },
    autoStopOnSilence: true,
    silenceTimeoutMs: 2000,
  });

  // Apply template when selected
  useEffect(() => {
    if (selectedTemplate && open) {
      setEpicTitle(selectedTemplate.name);
      setEpicWhy(selectedTemplate.description);
      setDeadline(addDays(new Date(), selectedTemplate.target_days));
      setThemeColor(selectedTemplate.theme_color || themeColors[0].id);
      
      // Map frequency to valid database values
      const mapFrequency = (freq: string): 'daily' | '5x_week' | '3x_week' | 'custom' => {
        if (freq === 'daily') return 'daily';
        if (freq === '5x_week') return '5x_week';
        if (freq === '3x_week') return '3x_week';
        if (freq === 'weekly') return '3x_week'; // Map weekly to 3x for backwards compat
        return 'custom';
      };

      const templateSuggestions: EpicSuggestion[] = selectedTemplate.habits.map((h, idx) => ({
        id: `template-${idx}`,
        type: 'habit' as const,
        title: h.title,
        description: '',
        difficulty: (h.difficulty || 'medium') as 'easy' | 'medium' | 'hard',
        frequency: mapFrequency(h.frequency || 'daily'),
        selected: true,
      }));
      setCustomHabits(templateSuggestions);
      // Template already has habits, go directly to timeline (will need to generate schedule)
      setStep('goal');
    }
  }, [selectedTemplate, open]);

  useEffect(() => {
    if (template && open) {
      setSelectedTemplate(template);
    }
  }, [template, open]);

  useEffect(() => {
    if (!open) {
      hasAutoGeneratedRef.current = false;
    }
  }, [open]);

  // Scroll to top when step changes
  useEffect(() => {
    if (scrollContainerRef.current) {
      scrollContainerRef.current.scrollTo({ top: 0, behavior: 'instant' });
    }
  }, [step]);

  const selectedSuggestions = useMemo(() => getSelectedSuggestions(), [getSelectedSuggestions]);
  const selectedHabits = useMemo(
    () => {
      // Use schedule rituals if available, otherwise fall back to suggestions
      if (schedule?.rituals) {
        return schedule.rituals.map(r => ({
          id: r.id,
          title: r.title,
          description: r.description,
          type: 'habit' as const,
          difficulty: r.difficulty,
          frequency: r.frequency,
          isSelected: true,
        }));
      }
      return [...selectedSuggestions.filter((s) => s.type === 'habit'), ...customHabits];
    },
    [schedule, selectedSuggestions, customHabits]
  );
  const selectedMilestones = useMemo(
    () => schedule?.milestones || selectedSuggestions.filter((s) => s.type === 'milestone'),
    [schedule, selectedSuggestions]
  );

  const calculateXP = useMemo(() => targetDays * EPIC_XP_REWARDS.XP_PER_DAY, [targetDays]);

  const handleGenerateTimeline = useCallback(async (
    answersOverride?: Record<string, string | number>,
    contextOverride?: string
  ) => {
    if (!goalInput.trim() || !deadline) return;
    tap();
    
    const deadlineStr = format(deadline, 'yyyy-MM-dd');
    // Use override if provided, then local state, then props
    const answersToUse = answersOverride 
      ?? (Object.keys(localClarificationAnswers).length > 0 ? localClarificationAnswers : clarificationAnswers);
    const contextToUse = contextOverride ?? localEpicContext ?? epicContext;
    
    const result = await generateSchedule({
      goal: goalInput,
      deadline: deadlineStr,
      clarificationAnswers: answersToUse,
      epicContext: contextToUse,
      timelineContext: timelineContext.trim() || undefined,
    });
    
    // Store original rituals for reset functionality
    if (result?.rituals) {
      setOriginalRituals([...result.rituals]);
    }
    
    // Auto-set story type and theme color from AI suggestions
    if (result?.suggestedStoryType) {
      setStoryType(result.suggestedStoryType);
    }
    if (result?.suggestedThemeColor) {
      setThemeColor(result.suggestedThemeColor);
    }
    
    if (!epicTitle) setEpicTitle(goalInput);
    setStep('timeline');
    success();
  }, [goalInput, deadline, clarificationAnswers, epicContext, localClarificationAnswers, localEpicContext, timelineContext, epicTitle, generateSchedule, tap, success]);

  const handleAdjustSchedule = useCallback(async (feedback: string) => {
    if (!schedule || !deadline) return;
    
    await adjustSchedule({
      goal: goalInput,
      deadline: format(deadline, 'yyyy-MM-dd'),
      adjustmentRequest: feedback,
      previousSchedule: {
        phases: schedule.phases,
        milestones: schedule.milestones,
        rituals: schedule.rituals,
      },
    });
  }, [schedule, deadline, goalInput, adjustSchedule]);

  const handleProceedToSuggestions = useCallback(() => {
    if (!schedule) return;
    setStep('suggestions');
    medium();
  }, [schedule, medium]);

  // After goal step, classify and potentially show clarification, then generate timeline
  const handleProceedToTimeline = useCallback(async () => {
    if (!goalInput.trim() || !deadline) return;
    tap();
    
    // Classify the goal to check if clarification is needed
    const result = await classify(goalInput);
    
    if (result?.type === 'epic' && result.needsClarification && result.epicClarifyingQuestions?.length) {
      // Show clarification UI
      setShowClarification(true);
    } else {
      // No clarification needed, proceed directly to timeline generation
      if (!epicTitle) setEpicTitle(goalInput);
      await handleGenerateTimeline();
    }
  }, [goalInput, deadline, epicTitle, classify, tap, handleGenerateTimeline]);

  // Handle clarification submission
  const handleClarificationSubmit = useCallback(async (answers: Record<string, string | number>) => {
    setLocalClarificationAnswers(answers);
    setShowClarification(false);
    
    // Re-classify with answers to get refined epic details
    const result = await clarifyEpic(goalInput, answers);
    const contextFromClarify = result?.epicContext;
    if (contextFromClarify) {
      setLocalEpicContext(contextFromClarify);
    }
    
    if (!epicTitle) setEpicTitle(goalInput);
    // Pass answers directly to avoid race condition with async state updates
    await handleGenerateTimeline(answers, contextFromClarify);
  }, [goalInput, clarifyEpic, epicTitle, handleGenerateTimeline]);

  // Skip clarification - go directly to timeline generation
  const handleSkipClarification = useCallback(async () => {
    setShowClarification(false);
    if (!epicTitle) setEpicTitle(goalInput);
    await handleGenerateTimeline();
  }, [goalInput, epicTitle, handleGenerateTimeline]);

  const handleProceedToReview = useCallback(() => {
    // Story type is now auto-set, no need to check
    setStep('review');
    medium();
  }, [medium]);

  const handleCreateEpic = useCallback(() => {
    if (selectedHabits.length === 0) {
      console.warn('Cannot create epic: no habits selected');
      return;
    }

    const habits = selectedHabits.map((h) => ({
      title: h.title,
      description: h.description,
      difficulty: h.difficulty,
      frequency: h.frequency || 'daily',
      custom_days: [],
      estimated_minutes: h.estimatedMinutes,
    }));

    // Include milestones with dates from schedule
    const milestones = schedule?.milestones.map(m => ({
      title: m.title,
      description: m.description,
      target_date: m.targetDate,
      milestone_percent: m.milestonePercent,
      is_postcard_milestone: m.isPostcardMilestone,
    }));

    // Include phases from schedule
    const phases = schedule?.phases.map(p => ({
      name: p.name,
      description: p.description,
      start_date: p.startDate,
      end_date: p.endDate,
      phase_order: p.phaseOrder,
    }));

    trackInteraction({
      interactionType: 'epic-creation',
      inputText: goalInput,
      aiResponse: { 
        totalSuggestions: suggestions?.length || 0,
        selectedHabits: selectedHabits.length,
        targetDays,
        storyType,
        hasSchedule: !!schedule,
      },
      userAction: 'accepted',
      detectedIntent: 'epic',
    });

    onCreateEpic({
      title: epicTitle || goalInput,
      description: epicWhy || undefined,
      target_days: targetDays,
      habits,
      milestones,
      phases,
      is_public: true,
      story_type_slug: storyType || undefined,
      theme_color: themeColor,
    });

    success();
  }, [selectedHabits, epicTitle, goalInput, epicWhy, targetDays, storyType, themeColor, schedule, onCreateEpic, success, trackInteraction, suggestions]);

  const handleBack = useCallback(() => {
    light();
    // Updated flow: goal -> timeline -> suggestions -> review
    if (step === 'timeline') setStep('goal');
    else if (step === 'suggestions') setStep('timeline');
    else if (step === 'review') setStep('suggestions');
  }, [step, light]);

  const handleClose = useCallback(() => {
    setStep('goal');
    setGoalInput(initialGoal);
    setDeadline(undefined);
    setTimelineContext('');
    setEpicTitle('');
    setEpicWhy('');
    setCustomHabits([]);
    setStoryType(null);
    setThemeColor(themeColors[0].id);
    setSelectedTemplate(null);
    setShowClarification(false);
    setLocalClarificationAnswers({});
    setLocalEpicContext(undefined);
    resetSuggestions();
    resetSchedule();
    resetClassification();
    onOpenChange(false);
  }, [onOpenChange, resetSuggestions, resetSchedule, resetClassification, initialGoal]);

  const handleVoiceToggle = useCallback(() => {
    if (isRecording) {
      stopRecording();
    } else {
      startRecording();
    }
    tap();
  }, [isRecording, startRecording, stopRecording, tap]);

  const steps: WizardStep[] = ['goal', 'timeline', 'suggestions', 'review'];
  const currentStepIndex = steps.indexOf(step);

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-lg max-h-[90vh] flex flex-col p-0">
        <DialogHeader className="p-6 pb-4">
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-primary" />
            Pathfinder
          </DialogTitle>
          <DialogDescription>
            {step === 'goal' && 'Set your goal and deadline'}
            {step === 'timeline' && 'Review your personalized timeline'}
            {step === 'suggestions' && 'Confirm your rituals and milestones'}
            {step === 'review' && 'Review and create your campaign'}
          </DialogDescription>
        </DialogHeader>

        {isAtEpicLimit && (
          <div className="px-6 pb-2">
            <CapacityWarningBanner isAtEpicLimit={isAtEpicLimit} isLoading={false} />
          </div>
        )}

        {/* Progress indicator */}
        <div className="px-6 pb-4">
          <div className="flex items-center justify-center gap-2">
            {steps.map((s, i) => (
              <div key={s} className="flex items-center">
                <div
                  className={cn(
                    'w-8 h-8 rounded-full flex items-center justify-center text-sm font-medium transition-all',
                    step === s
                      ? 'bg-primary text-primary-foreground'
                      : currentStepIndex > i
                      ? 'bg-primary/20 text-primary'
                      : 'bg-muted text-muted-foreground'
                  )}
                >
                  {currentStepIndex > i ? <Check className="w-4 h-4" /> : i + 1}
                </div>
                {i < steps.length - 1 && (
                  <div className={cn('w-4 h-0.5 mx-1', currentStepIndex > i ? 'bg-primary' : 'bg-muted')} />
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Step Content */}
        <div ref={scrollContainerRef} className="flex-1 min-h-0 overflow-y-auto overscroll-contain" style={{ WebkitOverflowScrolling: 'touch', touchAction: 'pan-y' }}>
          <AnimatePresence mode="wait">
            {/* Step 1: Goal & Deadline */}
            {step === 'goal' && (
              <motion.div
                key="goal"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="px-6 pb-6 space-y-4"
              >
                <div className="space-y-2">
                  <Label htmlFor="goal-input" className="text-base font-semibold">
                    What's your goal?
                  </Label>
                  <div className="relative">
                    <Textarea
                      id="goal-input"
                      placeholder="e.g., Pass the bar exam, Run a marathon, Learn Spanish"
                      value={isRecording ? goalInput + (interimText ? ' ' + interimText : '') : goalInput}
                      onChange={(e) => setGoalInput(e.target.value)}
                      rows={3}
                      className="pr-12 text-base"
                    />
                    <Button
                      size="icon"
                      variant={isRecording ? 'default' : 'ghost'}
                      className={cn(
                        'absolute right-2 top-2 h-8 w-8',
                        isRecording && 'animate-pulse bg-red-500 hover:bg-red-600'
                      )}
                      onClick={handleVoiceToggle}
                      disabled={isAutoStopping}
                    >
                      <Mic className="w-4 h-4" />
                    </Button>
                  </div>
                </div>

                {/* Timeline Context - Optional */}
                <div className="space-y-2">
                  <Label htmlFor="context-input" className="text-base font-semibold flex items-center gap-2">
                    List current experience
                    <span className="text-sm font-normal text-muted-foreground">(optional)</span>
                  </Label>
                  <Textarea
                    id="context-input"
                    placeholder="e.g., Already know basics, studying for 2 weeks, starting from scratch"
                    value={timelineContext}
                    onChange={(e) => setTimelineContext(e.target.value)}
                    rows={2}
                    className="text-base"
                  />
                </div>

                {/* Deadline picker */}
                <div className="space-y-2">
                  <Label className="text-base font-semibold flex items-center gap-2">
                    <Calendar className="w-4 h-4" />
                    When do you need to achieve this?
                  </Label>
                  <DeadlinePicker value={deadline} onChange={setDeadline} />
                </div>

                {/* AI Clarification Flow */}
                <AnimatePresence>
                  {showClarification && classification?.epicClarifyingQuestions && classification.epicClarifyingQuestions.length > 0 && (
                    <EpicClarificationFlow
                      goal={goalInput}
                      questions={classification.epicClarifyingQuestions}
                      onSubmit={handleClarificationSubmit}
                      onSkip={handleSkipClarification}
                      isLoading={isClassifying}
                    />
                  )}
                </AnimatePresence>

                {/* Continue button - hide when showing clarification */}
                {!showClarification && (
                  <Button
                    onClick={handleProceedToTimeline}
                    disabled={!goalInput.trim() || !deadline || isClassifying || isScheduleLoading}
                    className="w-full h-12 text-base"
                    size="lg"
                  >
                    {isClassifying ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        Analyzing your goal...
                      </>
                    ) : isScheduleLoading ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        Generating your plan...
                      </>
                    ) : (
                      <>
                        <Wand2 className="w-5 h-5 mr-2" />
                        Generate My Plan
                      </>
                    )}
                  </Button>
                )}

                {error && (
                  <p className="text-sm text-destructive text-center">{error}</p>
                )}
              </motion.div>
            )}

            {/* Step 2: Timeline Review */}
            {step === 'timeline' && schedule && deadline && (
              <motion.div
                key="timeline"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="flex flex-col h-full min-h-0"
              >
                <div className="flex-1 overflow-y-auto px-4 overscroll-contain" style={{ WebkitOverflowScrolling: 'touch', touchAction: 'pan-y' }}>
                  <div className="space-y-4 pb-4">
                    <TimelineView
                      feasibilityAssessment={schedule.feasibilityAssessment}
                      phases={schedule.phases}
                      milestones={schedule.milestones}
                      rituals={schedule.rituals}
                      weeklyHoursEstimate={schedule.weeklyHoursEstimate}
                      deadline={format(deadline!, 'yyyy-MM-dd')}
                      onMilestoneToggle={toggleMilestone}
                      onMilestoneDateChange={updateMilestoneDate}
                      postcardCount={postcardCount}
                      maxPostcards={maxPostcards}
                    />

                    {/* Adjustment input */}
                    <div className="pt-4 border-t">
                      <AdjustmentInput onSubmit={handleAdjustSchedule} isLoading={isScheduleLoading} />
                    </div>

                    {/* Actions */}
                    <div className="space-y-3 pt-2">
                      <Button onClick={handleProceedToSuggestions} className="w-full">
                        Continue with this plan
                        <ChevronRight className="w-4 h-4 ml-1" />
                      </Button>
                      <Button variant="ghost" onClick={handleBack} className="w-full">
                        <ChevronLeft className="w-4 h-4 mr-1" />
                        Back
                      </Button>
                    </div>
                  </div>
                </div>
              </motion.div>
            )}

            {/* Step 3: Suggestions Confirmation (was Step 4) */}
            {step === 'suggestions' && (
              <motion.div
                key="suggestions"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="flex flex-col h-full min-h-0"
              >
                <div className="flex-1 overflow-y-auto px-6 overscroll-contain" style={{ WebkitOverflowScrolling: 'touch', touchAction: 'pan-y' }}>
                  <div className="space-y-4 pb-4">
                    {/* Editable Rituals */}
                    {schedule?.rituals && (
                      <RitualEditor
                        rituals={schedule.rituals}
                        originalRituals={originalRituals}
                        onRitualsChange={setRituals}
                      />
                    )}

                    {/* Milestones */}
                    <div className="space-y-2">
                      <div className="flex items-center gap-2 text-sm font-medium">
                        <Flag className="w-4 h-4" />
                        Milestones ({selectedMilestones.length})
                      </div>
                      {selectedMilestones.map((m: any) => (
                        <div key={m.id} className="p-3 bg-amber-500/10 rounded-lg">
                          <div className="flex items-center justify-between">
                            <span className="font-medium">{m.title}</span>
                            <Badge variant="outline">
                              {m.targetDate ? format(parseISO(m.targetDate), 'MMM d') : `Week ${m.suggestedWeek}`}
                            </Badge>
                          </div>
                        </div>
                      ))}
                    </div>

                    {/* Postcard Preview */}
                    {schedule?.milestones && (
                      <PostcardPreview 
                        milestones={schedule.milestones} 
                        storyType={storyType}
                      />
                    )}
                  </div>
                </div>

                <div className="p-6 pt-4 border-t bg-background space-y-3">
                  <Button onClick={handleProceedToReview} className="w-full">
                    Continue to Review
                    <ChevronRight className="w-4 h-4 ml-1" />
                  </Button>
                  <Button variant="ghost" onClick={handleBack} className="w-full">
                    <ChevronLeft className="w-4 h-4 mr-1" />
                    Back to Timeline
                  </Button>
                </div>
              </motion.div>
            )}

            {/* Step 4: Review (was Step 5) */}
            {step === 'review' && (
              <motion.div
                key="review"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="flex flex-col h-full min-h-0"
              >
                <div className="flex-1 overflow-y-auto px-6 overscroll-contain" style={{ WebkitOverflowScrolling: 'touch', touchAction: 'pan-y' }}>
                  <div className="space-y-4 pb-4">
                    <div className="space-y-2">
                      <Label htmlFor="epic-why">Your Why</Label>
                      <Textarea
                        id="epic-why"
                        value={epicWhy}
                        onChange={(e) => setEpicWhy(e.target.value)}
                        placeholder="Why are you embarking on this campaign? What's your purpose?"
                        rows={3}
                      />
                      <p className="text-xs text-muted-foreground">
                        Define your purpose - this will fuel your motivation
                      </p>
                    </div>

                    {epicWhy.trim().length > 0 && (
                      <motion.div 
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="space-y-2"
                      >
                        <Label htmlFor="epic-title">Campaign Name</Label>
                        <Input
                          id="epic-title"
                          value={epicTitle}
                          onChange={(e) => setEpicTitle(e.target.value)}
                          placeholder="Name your campaign"
                        />
                      </motion.div>
                    )}

                    <div className="p-4 bg-gradient-to-r from-primary/10 to-purple-500/10 rounded-xl border border-primary/20">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <Zap className="w-5 h-5 text-primary" />
                          <span className="font-medium">Completion Reward</span>
                        </div>
                        <span className="text-xl font-bold text-primary">+{calculateXP} XP</span>
                      </div>
                      <p className="text-xs text-muted-foreground mt-1">
                        {targetDays} days • {selectedHabits.length} rituals • {selectedMilestones.length} milestones
                      </p>
                    </div>
                  </div>
                </div>

                <div className="p-6 pt-4 border-t bg-background space-y-3">
                  <Button
                    onClick={handleCreateEpic}
                    disabled={isCreating || selectedHabits.length === 0 || epicWhy.trim().length === 0 || epicTitle.trim().length === 0}
                    className="w-full bg-gradient-to-r from-primary to-purple-600"
                  >
                    {isCreating ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        Creating...
                      </>
                    ) : (
                      <>
                        <Target className="w-4 h-4 mr-2" />
                        Create Campaign
                      </>
                    )}
                  </Button>
                  <Button variant="ghost" onClick={handleBack} className="w-full">
                    <ChevronLeft className="w-4 h-4 mr-1" />
                    Back
                  </Button>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </DialogContent>
    </Dialog>
  );
}
