import { useState, useCallback, useMemo, useEffect, useRef } from 'react';
import { plannerPathfinderTheme } from '@/components/companion/plannerPathfinderTheme';
import { toast } from "@/components/ui/sonner";
import { motion, AnimatePresence } from 'framer-motion';
import { differenceInDays, parseISO, format, addDays } from 'date-fns';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';

import {
  Wand2,
  ChevronRight,
  ChevronLeft,
  Check,
  Loader2,
  Target,
  Mic,
  Calendar,
  Zap,
  Flag,
  X,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { useEpicSuggestions, type EpicSuggestion, type ClarificationAnswers } from '@/hooks/useEpicSuggestions';
import { useEpicTemplates, EpicTemplate } from '@/hooks/useEpicTemplates';
import { useUserAIContext } from '@/hooks/useUserAIContext';
import { useEpics } from '@/hooks/useEpics';
import { useAIInteractionTracker } from '@/hooks/useAIInteractionTracker';
import { useHapticFeedback } from '@/hooks/useHapticFeedback';
import { useJourneySchedule, type JourneyRitual } from '@/hooks/useJourneySchedule';
import { useIntentClassifier } from '@/hooks/useIntentClassifier';
import { RitualEditor } from './RitualEditor';
import { PostcardPreview } from './PostcardPreview';
import { CapacityWarningBanner } from '@/components/CapacityWarningBanner';
import { themeColors } from './StoryStep';
import { EpicClarificationFlow } from '@/features/tasks/components/EpicClarificationFlow';
import { DeadlinePicker } from '@/components/JourneyWizard/DeadlinePicker';
import { TimelineView } from '@/components/JourneyWizard/TimelineView';
import { AdjustmentInput } from '@/components/JourneyWizard/AdjustmentInput';
import { useVoiceInput } from '@/hooks/useVoiceInput';
import { useJourneysCompanionVisual } from '@/hooks/useJourneysCompanionVisual';
import { EPIC_XP_REWARDS } from '@/config/xpRewards';
import { hasReachedActiveCampaignLimit } from '@/features/epics/constants';
import type { StoryTypeSlug } from '@/types/narrativeTypes';
import type { ClarifyingQuestion } from '@/hooks/useIntentClassifier';
import { getDefaultMonthDaysForFrequency, getDefaultWeekdaysForFrequency } from '@/utils/habitSchedule';
import { CompanionImage, CompanionPortraitShell } from '@/components/CompanionImage';
import {
  isValidCampaignMilestonePercent,
  normalizeCampaignMilestonePercentArray,
} from '@/utils/campaignMilestones';

// Default clarification questions when AI doesn't provide any
const DEFAULT_CLARIFICATION_QUESTIONS: ClarifyingQuestion[] = [
  {
    id: 'experience_level',
    question: 'What is your current experience level?',
    type: 'select',
    options: ['Complete beginner', 'Some experience', 'Intermediate', 'Advanced'],
    required: true,
  },
  {
    id: 'daily_time',
    question: 'How much time can you dedicate daily?',
    type: 'text',
    placeholder: 'e.g., 1-2 hours, 30 minutes',
    required: true,
  },
  {
    id: 'priority_focus',
    question: 'What aspect is most important to you?',
    type: 'text',
    placeholder: 'e.g., speed, thoroughness, consistency',
    required: false,
  },
];

type WizardStep = 'goal' | 'timeline' | 'suggestions' | 'review';

interface PathfinderProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onCreateEpic: (data: {
    title: string;
    description?: string;
    target_days: number;
    habits: Array<{
      title: string;
      description?: string;
      difficulty: string;
      frequency: string;
      custom_days: number[];
      custom_month_days?: number[];
      estimated_minutes?: number;
      preferred_time?: string | null;
    }>;
    milestones?: Array<{
      title: string;
      description?: string;
      target_date: string;
      milestone_percent: number;
      is_postcard_milestone: boolean;
    }>;
    phases?: Array<{
      name: string;
      description: string;
      start_date: string;
      end_date: string;
      phase_order: number;
    }>;
    is_public?: boolean;
    story_type_slug?: StoryTypeSlug;
    theme_color?: string;
  }) => Promise<unknown> | void;
  isCreating: boolean;
  initialGoal?: string;
  initialTargetDays?: number;
  template?: EpicTemplate | null;
  showTemplatesFirst?: boolean;
  clarificationAnswers?: ClarificationAnswers;
  epicContext?: string;
}

export function Pathfinder({
  open,
  onOpenChange,
  onCreateEpic,
  isCreating,
  initialGoal = '',
  initialTargetDays,
  template,
  showTemplatesFirst: _showTemplatesFirst = false,
  clarificationAnswers,
  epicContext,
}: PathfinderProps) {
  const hasAutoGeneratedRef = useRef(false);
  const scrollContainerRef = useRef<HTMLDivElement>(null);
  const [step, setStep] = useState<WizardStep>('goal');
  const [goalInput, setGoalInput] = useState(initialGoal);
  const [deadline, setDeadline] = useState<Date | undefined>(undefined);
  
  // Timeline context state
  const [timelineContext, setTimelineContext] = useState('');
  
  const { preferences } = useUserAIContext();
  const { activeEpics } = useEpics({ enabled: open });
  const hasReachedCampaignLimit = hasReachedActiveCampaignLimit(activeEpics.length);
  const {
    companionLabel,
    imageUrl,
    focalX,
    focalY,
    element,
    usesPortraitShell,
  } = useJourneysCompanionVisual();
  const { trackInteraction } = useAIInteractionTracker();
  const { schedule, isLoading: isScheduleLoading, generateSchedule, adjustSchedule, toggleMilestone, updateMilestoneDate, reset: resetSchedule, setRituals, postcardCount, maxPostcards } = useJourneySchedule();
  const [originalRituals, setOriginalRituals] = useState<JourneyRitual[]>([]);
  
  // AI Clarification state
  const {
    classify,
    isClassifying,
    clarifyEpic,
    reset: resetClassification,
  } = useIntentClassifier({ useOrchestrator: false });
  const [showClarification, setShowClarification] = useState(false);
  const [clarificationQuestions, setClarificationQuestions] = useState<ClarifyingQuestion[]>([]);
  const [localClarificationAnswers, setLocalClarificationAnswers] = useState<Record<string, string | number>>({});
  const [localEpicContext, setLocalEpicContext] = useState<string | undefined>(undefined);
  const [isSubmittingCreate, setIsSubmittingCreate] = useState(false);
  
  const targetDays = useMemo(() => {
    if (deadline) {
      return Math.max(1, differenceInDays(deadline, new Date()));
    }
    if (initialTargetDays) return initialTargetDays;
    return preferences.epicDuration || 30;
  }, [deadline, initialTargetDays, preferences.epicDuration]);
  
  const [epicTitle, setEpicTitle] = useState('');
  const [epicWhy, setEpicWhy] = useState('');
  const [customHabits, setCustomHabits] = useState<EpicSuggestion[]>([]);
  const [storyType, setStoryType] = useState<StoryTypeSlug | null>(null);
  const [themeColor, setThemeColor] = useState(themeColors[0].id);
  const [selectedTemplate, setSelectedTemplate] = useState<EpicTemplate | null>(template || null);
  const { medium, success, light, tap } = useHapticFeedback();
  
  useEpicTemplates();
  const {
    suggestions,
    error,
    getSelectedSuggestions,
    reset: resetSuggestions,
  } = useEpicSuggestions();

  const [interimText, setInterimText] = useState('');
  
  const {
    isRecording,
    isAutoStopping,
    startRecording,
    stopRecording,
  } = useVoiceInput({
    onInterimResult: (text) => setInterimText(text),
    onFinalResult: (text) => {
      setGoalInput((prev) => (prev ? prev + ' ' + text : text).trim());
      setInterimText('');
      success();
    },
    autoStopOnSilence: true,
    silenceTimeoutMs: 2000,
  });

  // Apply template when selected
  useEffect(() => {
    if (selectedTemplate && open) {
      setEpicTitle(selectedTemplate.name);
      setEpicWhy(selectedTemplate.description);
      setDeadline(addDays(new Date(), selectedTemplate.target_days));
      setThemeColor(selectedTemplate.theme_color || themeColors[0].id);
      
      // Map frequency to valid database values
      const mapFrequency = (freq: string): 'daily' | '5x_week' | '3x_week' | 'monthly' | 'custom' => {
        if (freq === 'daily') return 'daily';
        if (freq === '5x_week') return '5x_week';
        if (freq === '3x_week') return '3x_week';
        if (freq === 'monthly') return 'monthly';
        if (freq === 'weekly') return '3x_week'; // Map weekly to 3x for backwards compat
        return 'custom';
      };

      const templateSuggestions: EpicSuggestion[] = selectedTemplate.habits.map((h, idx) => ({
        id: `template-${idx}`,
        type: 'habit' as const,
        title: h.title,
        description: '',
        difficulty: (h.difficulty || 'medium') as 'easy' | 'medium' | 'hard',
        frequency: mapFrequency(h.frequency || 'daily'),
        selected: true,
      }));
      setCustomHabits(templateSuggestions);
      // Template already has habits, go directly to timeline (will need to generate schedule)
      setStep('goal');
    }
  }, [selectedTemplate, open]);

  useEffect(() => {
    if (template && open) {
      setSelectedTemplate(template);
    }
  }, [template, open]);

  useEffect(() => {
    if (!open) {
      hasAutoGeneratedRef.current = false;
      setIsSubmittingCreate(false);
    }
  }, [open]);

  // Scroll to top when step changes
  useEffect(() => {
    if (scrollContainerRef.current) {
      scrollContainerRef.current.scrollTo({ top: 0, behavior: 'instant' });
    }
  }, [step]);

  const selectedSuggestions = useMemo(() => getSelectedSuggestions(), [getSelectedSuggestions]);
  const selectedHabits = useMemo(
    () => {
      // Use schedule rituals if available, otherwise fall back to suggestions
      if (schedule?.rituals) {
        console.log('[Pathfinder] Mapping schedule rituals:', schedule.rituals.length, schedule.rituals.map(r => ({ title: r.title, estimatedMinutes: r.estimatedMinutes, preferredTime: r.preferredTime })));
        return schedule.rituals.map(r => ({
          id: r.id,
          title: r.title,
          description: r.description,
          type: 'habit' as const,
          difficulty: r.difficulty,
          frequency: r.frequency,
          customDays: r.customDays,
          customMonthDays: r.customMonthDays,
          customPeriod: r.customPeriod,
          estimatedMinutes: r.estimatedMinutes,
          preferredTime: r.preferredTime ?? null,
          isSelected: true,
        }));
      }
      return [...selectedSuggestions.filter((s) => s.type === 'habit'), ...customHabits];
    },
    [schedule, selectedSuggestions, customHabits]
  );
  const selectedMilestones = useMemo(
    () => schedule?.milestones || selectedSuggestions.filter((s) => s.type === 'milestone'),
    [schedule, selectedSuggestions]
  );

  const calculateXP = useMemo(() => targetDays * EPIC_XP_REWARDS.XP_PER_DAY, [targetDays]);

  const handleGenerateTimeline = useCallback(async (
    answersOverride?: Record<string, string | number>,
    contextOverride?: string
  ) => {
    if (!goalInput.trim() || !deadline) return;
    tap();
    
    const deadlineStr = format(deadline, 'yyyy-MM-dd');
    // Use override if provided, then local state, then props
    const answersToUse = answersOverride 
      ?? (Object.keys(localClarificationAnswers).length > 0 ? localClarificationAnswers : clarificationAnswers);
    const contextToUse = contextOverride ?? localEpicContext ?? epicContext;
    
    const result = await generateSchedule({
      goal: goalInput,
      deadline: deadlineStr,
      clarificationAnswers: answersToUse,
      epicContext: contextToUse,
      timelineContext: timelineContext.trim() || undefined,
    });
    
    // Only proceed if generation was successful
    if (!result) {
      toast.error('Failed to build timeline', {
        description: 'Please try again or adjust your goal'
      });
      return;
    }
    
    // Store original rituals for reset functionality
    if (result.rituals) {
      setOriginalRituals([...result.rituals]);
    }
    
    // Auto-set story type and theme color from AI suggestions
    if (result.suggestedStoryType) {
      setStoryType(result.suggestedStoryType);
    }
    if (result.suggestedThemeColor) {
      setThemeColor(result.suggestedThemeColor);
    }
    
    if (!epicTitle) setEpicTitle(goalInput);
    setStep('timeline');
    success();
  }, [goalInput, deadline, clarificationAnswers, epicContext, localClarificationAnswers, localEpicContext, timelineContext, epicTitle, generateSchedule, tap, success]);

  const handleAdjustSchedule = useCallback(async (feedback: string) => {
    if (!schedule || !deadline) return;
    
    const result = await adjustSchedule({
      goal: goalInput,
      deadline: format(deadline, 'yyyy-MM-dd'),
      adjustmentRequest: feedback,
      previousSchedule: {
        phases: schedule.phases,
        milestones: schedule.milestones,
        rituals: schedule.rituals,
      },
    });
    
    if (result) {
      success();
      toast.success('Schedule updated!', {
        description: feedback.toLowerCase().includes('intensive') 
          ? 'Made your plan more intensive'
          : feedback.toLowerCase().includes('less') || feedback.toLowerCase().includes('breathing')
          ? 'Made your plan more relaxed'
          : 'Adjusted based on your feedback'
      });
    } else {
      light();
      toast.error('Failed to adjust schedule', {
        description: 'Please try again'
      });
    }
  }, [schedule, deadline, goalInput, adjustSchedule, success, light]);

  const handleProceedToSuggestions = useCallback(() => {
    if (!schedule) return;
    setStep('suggestions');
    medium();
  }, [schedule, medium]);

  // After goal step, classify and potentially show clarification, then generate timeline
  const handleProceedToTimeline = useCallback(async () => {
    if (!goalInput.trim() || !deadline) return;
    tap();
    
    // Classify the goal to check if clarification is needed
    const result = await classify(goalInput);
    
    // Debug logging for classification results
    console.log('[Pathfinder] Classification result:', {
      input: goalInput,
      type: result?.type,
      confidence: result?.confidence,
      needsClarification: result?.needsClarification,
      questionsCount: result?.epicClarifyingQuestions?.length,
      epicContext: result?.epicContext,
    });
    
    // For epics, ALWAYS show clarification - use AI questions or fallback defaults
    if (result?.type === 'epic') {
      const questions = result.epicClarifyingQuestions?.length 
        ? result.epicClarifyingQuestions 
        : DEFAULT_CLARIFICATION_QUESTIONS;
      setClarificationQuestions(questions);
      setShowClarification(true);
    } else {
      // Non-epic types proceed directly to timeline generation
      if (!epicTitle) setEpicTitle(goalInput);
      await handleGenerateTimeline();
    }
  }, [goalInput, deadline, epicTitle, classify, tap, handleGenerateTimeline]);

  // Handle clarification submission
  const handleClarificationSubmit = useCallback(async (answers: Record<string, string | number>) => {
    setLocalClarificationAnswers(answers);
    setShowClarification(false);
    
    // Re-classify with answers to get refined epic details
    const result = await clarifyEpic(goalInput, answers);
    const contextFromClarify = result?.epicContext;
    if (contextFromClarify) {
      setLocalEpicContext(contextFromClarify);
    }
    
    if (!epicTitle) setEpicTitle(goalInput);
    // Pass answers directly to avoid race condition with async state updates
    await handleGenerateTimeline(answers, contextFromClarify);
  }, [goalInput, clarifyEpic, epicTitle, handleGenerateTimeline]);

  // Skip clarification - go directly to timeline generation
  const handleSkipClarification = useCallback(async () => {
    setShowClarification(false);
    if (!epicTitle) setEpicTitle(goalInput);
    await handleGenerateTimeline();
  }, [goalInput, epicTitle, handleGenerateTimeline]);

  const handleProceedToReview = useCallback(() => {
    // Story type is now auto-set, no need to check
    setStep('review');
    medium();
  }, [medium]);

  const handleCreateEpic = useCallback(async () => {
    if (selectedHabits.length === 0 || isSubmittingCreate || isCreating) {
      console.warn('Cannot create epic: no habits selected');
      return;
    }

    const habits = selectedHabits.map((h) => ({
      title: h.title,
      description: h.description,
      difficulty: h.difficulty,
      frequency: h.frequency || 'daily',
      custom_days: h.customDays || getDefaultWeekdaysForFrequency(h.frequency || 'daily'),
      custom_month_days: h.customMonthDays || getDefaultMonthDaysForFrequency(h.frequency || 'daily'),
      estimated_minutes: h.estimatedMinutes,
      preferred_time: h.preferredTime ?? null,
    }));

    // Log for debugging ritual count issues
    console.log('[Pathfinder] Creating epic with habits:', habits.length, habits.map(h => h.title));
    if (habits.length < 2 && schedule?.rituals && schedule.rituals.length > habits.length) {
      console.warn('[Pathfinder] Habit count mismatch! Schedule has', schedule.rituals.length, 'but habits array has', habits.length);
    }

    const normalizedMilestonePercents = schedule?.milestones
      ? normalizeCampaignMilestonePercentArray(schedule.milestones.map((m) => m.milestonePercent))
      : [];

    // Include milestones with dates from schedule
    const milestones = schedule?.milestones.map((m, index) => ({
      title: m.title,
      description: m.description,
      target_date: m.targetDate,
      milestone_percent: normalizedMilestonePercents[index],
      is_postcard_milestone: m.isPostcardMilestone,
    }));

    if (milestones?.some((milestone) => !isValidCampaignMilestonePercent(milestone.milestone_percent))) {
      toast.error('Campaign plan needs an update', {
        description: 'One of the generated milestones had an invalid percentage. Rebuild the plan and try again.',
      });
      return;
    }
    
    console.log('[Pathfinder] Creating epic with milestones:', milestones?.length || 0, milestones);

    // Include phases from schedule
    const phases = schedule?.phases.map(p => ({
      name: p.name,
      description: p.description,
      start_date: p.startDate,
      end_date: p.endDate,
      phase_order: p.phaseOrder,
    }));

    if (phases?.some((phase) => !phase.start_date || !phase.end_date || !Number.isFinite(Number(phase.phase_order)))) {
      toast.error('Campaign plan needs dates', {
        description: 'One of the generated phases is missing dates. Rebuild the plan and try again.',
      });
      return;
    }

    setIsSubmittingCreate(true);

    trackInteraction({
      interactionType: 'epic-creation',
      inputText: goalInput,
      aiResponse: { 
        totalSuggestions: suggestions?.length || 0,
        selectedHabits: selectedHabits.length,
        targetDays,
        storyType,
        hasSchedule: !!schedule,
      },
      userAction: 'accepted',
      detectedIntent: 'epic',
    });

    try {
      await Promise.resolve(onCreateEpic({
        title: epicTitle || goalInput,
        description: epicWhy || undefined,
        target_days: targetDays,
        habits,
        milestones,
        phases,
        is_public: true,
        story_type_slug: storyType || undefined,
        theme_color: themeColor,
      }));

      success();
    } finally {
      setIsSubmittingCreate(false);
    }
  }, [selectedHabits, isSubmittingCreate, isCreating, epicTitle, goalInput, epicWhy, targetDays, storyType, themeColor, schedule, onCreateEpic, success, trackInteraction, suggestions]);

  const handleBack = useCallback(() => {
    light();
    // Updated flow: goal -> timeline -> suggestions -> review
    if (step === 'timeline') setStep('goal');
    else if (step === 'suggestions') setStep('timeline');
    else if (step === 'review') setStep('suggestions');
  }, [step, light]);

  const handleClose = useCallback(() => {
    setStep('goal');
    setGoalInput(initialGoal);
    setDeadline(undefined);
    setTimelineContext('');
    setEpicTitle('');
    setEpicWhy('');
    setCustomHabits([]);
    setStoryType(null);
    setThemeColor(themeColors[0].id);
    setSelectedTemplate(null);
    setShowClarification(false);
    setClarificationQuestions([]);
    setLocalClarificationAnswers({});
    setLocalEpicContext(undefined);
    resetSuggestions();
    resetSchedule();
    resetClassification();
    onOpenChange(false);
  }, [onOpenChange, resetSuggestions, resetSchedule, resetClassification, initialGoal]);

  const handleVoiceToggle = useCallback(() => {
    if (isRecording) {
      stopRecording();
    } else {
      startRecording();
    }
    tap();
  }, [isRecording, startRecording, stopRecording, tap]);

  const steps: WizardStep[] = ['goal', 'timeline', 'suggestions', 'review'];
  const currentStepIndex = steps.indexOf(step);
  const stepDescriptions: Record<WizardStep, string> = {
    goal: 'Set your goal and deadline',
    timeline: 'Review your personalized timeline',
    suggestions: 'Confirm your rituals and milestones',
    review: 'Review and create your campaign',
  };
  const headerAvatar = usesPortraitShell ? (
    <CompanionPortraitShell
      src={imageUrl}
      element={element}
      className="h-12 w-12 overflow-hidden rounded-full border border-white/[0.15] shadow-[0_18px_32px_-26px_rgba(0,0,0,0.95)]"
    >
      <CompanionImage
        src={imageUrl}
        alt={companionLabel}
        fit="portrait"
        element={element}
        focalX={focalX}
        focalY={focalY}
        className="rounded-full"
      />
    </CompanionPortraitShell>
  ) : (
    <div className="h-12 w-12 overflow-hidden rounded-full border border-white/[0.15] bg-white/10 shadow-[0_18px_32px_-26px_rgba(0,0,0,0.95)]">
      <CompanionImage
        src={imageUrl}
        alt={companionLabel}
        element={element}
        focalX={focalX}
        focalY={focalY}
        className="rounded-full"
      />
    </div>
  );

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="w-[calc(100vw-1rem)] max-w-[calc(100vw-1rem)] border-none bg-transparent p-0 shadow-none sm:max-w-3xl" hideCloseButton>
        <div
          className={cn(plannerPathfinderTheme.shell, "mx-auto w-full")}
          data-tour="pathfinder-campaign-builder"
          data-testid="pathfinder-shell"
        >
          <div className={plannerPathfinderTheme.shellGloss} />
          <div className={plannerPathfinderTheme.shellGlow} />

          <div className={cn(plannerPathfinderTheme.shellBody, "h-[min(86vh,52rem)] min-h-[34rem]")}>
            <div className={plannerPathfinderTheme.headerBar} data-testid="pathfinder-header">
              <div className="relative shrink-0">
                {headerAvatar}
                <span
                  aria-hidden="true"
                  className="pointer-events-none absolute inset-[-18%] rounded-full bg-[radial-gradient(circle,rgba(125,211,252,0.3),transparent_70%)] blur-lg"
                />
              </div>
              <DialogHeader className="min-w-0 flex-1 space-y-1 text-left">
                <DialogTitle className="text-xl text-white">Pathfinder</DialogTitle>
                <DialogDescription className="text-sm text-white/[0.68]">
                  {stepDescriptions[step]}
                </DialogDescription>
              </DialogHeader>
              <Button
                type="button"
                size="icon"
                variant="outline"
                className={cn("h-10 w-10 shrink-0", plannerPathfinderTheme.headerIconButton)}
                onClick={handleClose}
                aria-label="Close Pathfinder"
              >
                <X className="h-4 w-4" />
              </Button>
            </div>

            {hasReachedCampaignLimit && (
              <div className="mt-3">
                <CapacityWarningBanner
                  isAtEpicLimit={hasReachedCampaignLimit}
                  isLoading={false}
                  className="rounded-[1.5rem] border-[3px] border-[#9a4718] bg-[#ffd9bf] px-4 py-3 text-[#8a2716] shadow-[0_8px_0_rgba(154,71,24,0.18)]"
                />
              </div>
            )}

            <div
              className={cn(plannerPathfinderTheme.mutedPanel, "mt-3 px-4 py-3")}
              data-testid="pathfinder-progress"
            >
              <div className="flex items-center justify-center gap-2 sm:gap-3">
                {steps.map((s, i) => {
                  const isComplete = currentStepIndex > i;
                  const isActive = step === s;

                  return (
                    <div key={s} className="flex items-center">
                      <div
                        className={cn(
                          "flex h-9 w-9 items-center justify-center rounded-full border-[3px] text-sm font-semibold transition-all",
                          isActive
                            ? "border-[#6b3416] bg-[linear-gradient(180deg,#fff8e8_0%,#ffcf6e_100%)] text-[#5d2a0f] shadow-[0_5px_0_rgba(77,40,17,0.35)]"
                            : isComplete
                              ? "border-[#315114] bg-[linear-gradient(180deg,#d7ff86_0%,#9fda3f_100%)] text-[#183304] shadow-[0_5px_0_rgba(49,81,20,0.28)]"
                              : "border-[#8d481c]/30 bg-white/55 text-[#8d481c]/65",
                        )}
                      >
                        {isComplete ? <Check className="h-4 w-4" /> : i + 1}
                      </div>
                      {i < steps.length - 1 && (
                        <div
                          className={cn(
                            "mx-1.5 h-1 w-6 rounded-full sm:w-8",
                            isComplete ? "bg-[#a6de45]" : "bg-[#8d481c]/20",
                          )}
                        />
                      )}
                    </div>
                  );
                })}
              </div>
            </div>

            <div className={plannerPathfinderTheme.contentWell}>
              <AnimatePresence mode="wait">
                {step === 'goal' && (
                  <motion.div
                    key="goal"
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -20 }}
                    className="flex h-full min-h-0 flex-col"
                  >
                    <div
                      ref={scrollContainerRef}
                      className="flex-1 min-h-0 overflow-y-auto overscroll-contain px-4 sm:px-5"
                      style={{ WebkitOverflowScrolling: 'touch', touchAction: 'pan-y' }}
                    >
                      <div className="space-y-4 py-4 text-[#4f240c]">
                        <div className={cn(plannerPathfinderTheme.raisedPanel, "space-y-3 p-4")}>
                          <Label htmlFor="goal-input" className="text-base font-semibold text-[#5d2a0f]">
                            What's your goal?
                          </Label>
                          <div className="relative">
                            <Textarea
                              id="goal-input"
                              placeholder="e.g., Pass the bar exam, Run a marathon, Learn Spanish"
                              value={isRecording ? goalInput + (interimText ? ' ' + interimText : '') : goalInput}
                              onChange={(e) => setGoalInput(e.target.value)}
                              rows={3}
                              className={cn(plannerPathfinderTheme.textField, "min-h-[132px] pr-14 text-base")}
                            />
                            <Button
                              size="icon"
                              variant={isRecording ? 'default' : 'ghost'}
                              className={cn(
                                "absolute right-3 top-3 h-10 w-10 rounded-full border-[3px] border-[#4d2811] bg-white/65 text-[#7f3b12] hover:bg-white/80",
                                isRecording && "animate-pulse border-[#7f1616] bg-[linear-gradient(180deg,#ffb8a7_0%,#ff7a59_100%)] text-[#4c0f0f]",
                              )}
                              onClick={handleVoiceToggle}
                              disabled={isAutoStopping}
                              aria-label={isRecording ? "Stop voice input" : "Start voice input"}
                            >
                              <Mic className="w-4 h-4" />
                            </Button>
                          </div>
                        </div>

                        <div className={cn(plannerPathfinderTheme.mutedPanel, "space-y-3 p-4")}>
                          <Label htmlFor="context-input" className="flex items-center gap-2 text-base font-semibold text-[#5d2a0f]">
                            List current experience
                            <span className="text-sm font-normal text-[#7f4a1d]/80">(optional)</span>
                          </Label>
                          <Textarea
                            id="context-input"
                            placeholder="e.g., Already know basics, studying for 2 weeks, starting from scratch"
                            value={timelineContext}
                            onChange={(e) => setTimelineContext(e.target.value)}
                            rows={2}
                            className={cn(plannerPathfinderTheme.textField, "min-h-[108px] text-base")}
                          />
                        </div>

                        <div className={cn(plannerPathfinderTheme.raisedPanel, "space-y-3 p-4")}>
                          <Label className="flex items-center gap-2 text-base font-semibold text-[#5d2a0f]">
                            <Calendar className="w-4 h-4 text-[#8d481c]" />
                            When do you need to achieve this?
                          </Label>
                          <DeadlinePicker value={deadline} onChange={setDeadline} />
                        </div>

                        <AnimatePresence>
                          {showClarification && clarificationQuestions.length > 0 && (
                            <EpicClarificationFlow
                              goal={goalInput}
                              questions={clarificationQuestions}
                              onSubmit={handleClarificationSubmit}
                              onSkip={handleSkipClarification}
                              isLoading={isClassifying}
                              variant="planner"
                            />
                          )}
                        </AnimatePresence>
                      </div>
                    </div>

                    {!showClarification && (
                      <div className={cn(plannerPathfinderTheme.footerBar, "space-y-3")} data-testid="pathfinder-footer">
                        <Button
                          onClick={handleProceedToTimeline}
                          disabled={!goalInput.trim() || !deadline || isClassifying || isScheduleLoading}
                          className={cn(plannerPathfinderTheme.primaryButton, "h-12 w-full text-base")}
                          size="lg"
                        >
                          {isClassifying ? (
                            <>
                              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                              Analyzing your goal...
                            </>
                          ) : isScheduleLoading ? (
                            <>
                              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                              Building your plan...
                            </>
                          ) : (
                            <>
                              <Wand2 className="mr-2 h-5 w-5" />
                              Build My Plan
                            </>
                          )}
                        </Button>
                        {error ? (
                          <p className="text-center text-sm text-[#8a2716]">{error}</p>
                        ) : null}
                      </div>
                    )}
                  </motion.div>
                )}

                {step === 'timeline' && schedule && deadline && (
                  <motion.div
                    key="timeline"
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -20 }}
                    className="flex h-full min-h-0 flex-col"
                  >
                    <div
                      ref={scrollContainerRef}
                      className="flex-1 min-h-0 overflow-y-auto overscroll-contain px-4 sm:px-5"
                      style={{ WebkitOverflowScrolling: 'touch', touchAction: 'pan-y' }}
                    >
                      <div className="space-y-4 py-4 text-[#4f240c]">
                        <TimelineView
                          feasibilityAssessment={schedule.feasibilityAssessment}
                          phases={schedule.phases}
                          milestones={schedule.milestones}
                          rituals={schedule.rituals}
                          weeklyHoursEstimate={schedule.weeklyHoursEstimate}
                          executionModel={schedule.executionModel}
                          deadline={format(deadline!, 'yyyy-MM-dd')}
                          onMilestoneToggle={toggleMilestone}
                          onMilestoneDateChange={updateMilestoneDate}
                          postcardCount={postcardCount}
                          maxPostcards={maxPostcards}
                        />
                        <AdjustmentInput onSubmit={handleAdjustSchedule} isLoading={isScheduleLoading} />
                      </div>
                    </div>

                    <div className={cn(plannerPathfinderTheme.footerBar, "space-y-3")} data-testid="pathfinder-footer">
                      <Button
                        onClick={handleProceedToSuggestions}
                        className={cn(plannerPathfinderTheme.primaryButton, "w-full")}
                      >
                        Continue with this plan
                        <ChevronRight className="ml-1 h-4 w-4" />
                      </Button>
                      <Button
                        variant="outline"
                        onClick={handleBack}
                        className={cn(plannerPathfinderTheme.outlineButton, "w-full")}
                      >
                        <ChevronLeft className="mr-1 h-4 w-4" />
                        Back
                      </Button>
                    </div>
                  </motion.div>
                )}

                {step === 'suggestions' && (
                  <motion.div
                    key="suggestions"
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -20 }}
                    className="flex h-full min-h-0 flex-col"
                  >
                    <div
                      ref={scrollContainerRef}
                      className="flex-1 min-h-0 overflow-y-auto overscroll-contain px-4 sm:px-5"
                      style={{ WebkitOverflowScrolling: 'touch', touchAction: 'pan-y' }}
                    >
                      <div className="space-y-4 py-4 text-[#4f240c]">
                        {schedule?.rituals && (
                          <RitualEditor
                            rituals={schedule.rituals}
                            originalRituals={originalRituals}
                            onRitualsChange={setRituals}
                          />
                        )}

                        <div className={cn(plannerPathfinderTheme.raisedPanel, "space-y-3 p-4")}>
                          <div className="flex items-center gap-2 text-sm font-semibold text-[#5d2a0f]">
                            <Flag className="h-4 w-4 text-[#8d481c]" />
                            Milestones ({selectedMilestones.length})
                          </div>
                          {selectedMilestones.map((m: any) => (
                            <div key={m.id} className={cn(plannerPathfinderTheme.mutedPanel, "flex items-center justify-between gap-3 p-3")}>
                              <span className="font-medium">{m.title}</span>
                              <Badge variant="outline" className={plannerPathfinderTheme.chip}>
                                {m.targetDate ? format(parseISO(m.targetDate), 'MMM d') : `Week ${m.suggestedWeek}`}
                              </Badge>
                            </div>
                          ))}
                        </div>

                        {schedule?.milestones && (
                          <PostcardPreview
                            milestones={schedule.milestones}
                            storyType={storyType}
                          />
                        )}
                      </div>
                    </div>

                    <div className={cn(plannerPathfinderTheme.footerBar, "space-y-3")} data-testid="pathfinder-footer">
                      <Button
                        onClick={handleProceedToReview}
                        className={cn(plannerPathfinderTheme.primaryButton, "w-full")}
                      >
                        Continue to Review
                        <ChevronRight className="ml-1 h-4 w-4" />
                      </Button>
                      <Button
                        variant="outline"
                        onClick={handleBack}
                        className={cn(plannerPathfinderTheme.outlineButton, "w-full")}
                      >
                        <ChevronLeft className="mr-1 h-4 w-4" />
                        Back to Timeline
                      </Button>
                    </div>
                  </motion.div>
                )}

                {step === 'review' && (
                  <motion.div
                    key="review"
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -20 }}
                    className="flex h-full min-h-0 flex-col"
                  >
                    <div
                      ref={scrollContainerRef}
                      className="flex-1 min-h-0 overflow-y-auto overscroll-contain px-4 sm:px-5"
                      style={{ WebkitOverflowScrolling: 'touch', touchAction: 'pan-y' }}
                    >
                      <div className="space-y-4 py-4 text-[#4f240c]">
                        <div className={cn(plannerPathfinderTheme.raisedPanel, "space-y-3 p-4")}>
                          <Label htmlFor="epic-why" className="text-[#5d2a0f]">Your Why</Label>
                          <Textarea
                            id="epic-why"
                            value={epicWhy}
                            onChange={(e) => setEpicWhy(e.target.value)}
                            placeholder="Why are you embarking on this campaign? What's your purpose?"
                            rows={3}
                            className={cn(plannerPathfinderTheme.textField, "min-h-[132px]")}
                          />
                          <p className="text-xs text-[#7f4a1d]/80">
                            Define your purpose - this will fuel your motivation
                          </p>
                        </div>

                        {epicWhy.trim().length > 0 && (
                          <motion.div
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            className={cn(plannerPathfinderTheme.mutedPanel, "space-y-3 p-4")}
                          >
                            <Label htmlFor="epic-title" className="text-[#5d2a0f]">Campaign Name</Label>
                            <Input
                              id="epic-title"
                              value={epicTitle}
                              onChange={(e) => setEpicTitle(e.target.value)}
                              placeholder="Name your campaign"
                              className={plannerPathfinderTheme.textField}
                            />
                          </motion.div>
                        )}

                        <div className={cn(plannerPathfinderTheme.successCard, "p-4")}>
                          <div className="flex items-center justify-between gap-3">
                            <div className="flex items-center gap-2">
                              <Zap className="h-5 w-5 text-[#315114]" />
                              <span className="font-medium">Completion Reward</span>
                            </div>
                            <span className="text-xl font-bold">+{calculateXP} XP</span>
                          </div>
                          <p className="mt-1 text-xs text-[#315114]/80">
                            {targetDays} days • {selectedHabits.length} rituals • {selectedMilestones.length} milestones
                          </p>
                        </div>
                      </div>
                    </div>

                    <div className={cn(plannerPathfinderTheme.footerBar, "space-y-3")} data-testid="pathfinder-footer">
                      <Button
                        onClick={handleCreateEpic}
                        disabled={hasReachedCampaignLimit || isCreating || isSubmittingCreate || selectedHabits.length === 0 || epicWhy.trim().length === 0 || epicTitle.trim().length === 0}
                        className={cn(plannerPathfinderTheme.primaryButton, "w-full")}
                      >
                        {isCreating || isSubmittingCreate ? (
                          <>
                            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                            Creating...
                          </>
                        ) : (
                          <>
                            <Target className="mr-2 h-4 w-4" />
                            Create Campaign
                          </>
                        )}
                      </Button>
                      <Button
                        variant="outline"
                        onClick={handleBack}
                        className={cn(plannerPathfinderTheme.outlineButton, "w-full")}
                      >
                        <ChevronLeft className="mr-1 h-4 w-4" />
                        Back
                      </Button>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
