export const QUEST_LAUNCHER_SIDE_INSET_PX = 16;
export const QUEST_LAUNCHER_TOP_OFFSET_PX = 80;
export const QUEST_LAUNCHER_BOTTOM_GAP_PX = 24;
export const QUEST_LAUNCHER_BUTTON_SIZE_PX = 44;
export const QUEST_LAUNCHER_STACK_GAP_PX = 10;
export const QUEST_LAUNCHER_CLEARANCE_BUFFER_PX = 8;

export const QUEST_LAUNCHER_STACK_HEIGHT_PX =
  (QUEST_LAUNCHER_BUTTON_SIZE_PX * 2) + QUEST_LAUNCHER_STACK_GAP_PX;

export const QUEST_LAUNCHER_SCROLL_CLEARANCE_PX =
  QUEST_LAUNCHER_STACK_HEIGHT_PX + QUEST_LAUNCHER_BOTTOM_GAP_PX + QUEST_LAUNCHER_CLEARANCE_BUFFER_PX;
