-- Add analytics tracking columns to referral_codes table
ALTER TABLE referral_codes 
ADD COLUMN IF NOT EXISTS total_signups INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_conversions INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_revenue DECIMAL(10,2) DEFAULT 0;

-- Add referral_code_id to referral_payouts table
ALTER TABLE referral_payouts
ADD COLUMN IF NOT EXISTS referral_code_id UUID REFERENCES referral_codes(id) ON DELETE CASCADE;

-- Create index for better query performance
CREATE INDEX IF NOT EXISTS idx_referral_payouts_code_id ON referral_payouts(referral_code_id);

COMMENT ON COLUMN referral_codes.total_signups IS 'Total number of users who signed up using this code';
COMMENT ON COLUMN referral_codes.total_conversions IS 'Total number of paid subscriptions from this code';
COMMENT ON COLUMN referral_codes.total_revenue IS 'Total subscription revenue generated by this code';
COMMENT ON COLUMN referral_payouts.referral_code_id IS 'Links payout to the referral code that earned it';