import { useState, useCallback, useMemo, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { differenceInDays, parseISO, format, addDays } from 'date-fns';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  Sparkles,
  Wand2,
  ChevronRight,
  ChevronLeft,
  Check,
  Loader2,
  Target,
  Mic,
  Calendar,
  Zap,
  Repeat,
  Flag,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { useEpicSuggestions, type EpicSuggestion, type ClarificationAnswers } from '@/hooks/useEpicSuggestions';
import { useEpicTemplates, EpicTemplate } from '@/hooks/useEpicTemplates';
import { useUserAIContext } from '@/hooks/useUserAIContext';
import { useAIInteractionTracker } from '@/hooks/useAIInteractionTracker';
import { useHapticFeedback } from '@/hooks/useHapticFeedback';
import { useJourneySchedule } from '@/hooks/useJourneySchedule';
import { SuggestionCard } from './SuggestionCard';
import { CapacityWarningBanner } from '@/components/CapacityWarningBanner';
import { StoryStep, themeColors } from './StoryStep';
import { DeadlinePicker } from '@/components/JourneyWizard/DeadlinePicker';
import { TimelineView } from '@/components/JourneyWizard/TimelineView';
import { AdjustmentInput } from '@/components/JourneyWizard/AdjustmentInput';
import { useVoiceInput } from '@/hooks/useVoiceInput';
import { EPIC_XP_REWARDS } from '@/config/xpRewards';
import type { StoryTypeSlug } from '@/types/narrativeTypes';

type WizardStep = 'goal' | 'timeline' | 'suggestions' | 'story' | 'review';

interface SmartEpicWizardProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onCreateEpic: (data: {
    title: string;
    description?: string;
    target_days: number;
    habits: Array<{
      title: string;
      difficulty: string;
      frequency: string;
      custom_days: number[];
    }>;
    milestones?: Array<{
      title: string;
      description?: string;
      target_date: string;
      milestone_percent: number;
      is_postcard_milestone: boolean;
    }>;
    phases?: Array<{
      name: string;
      description: string;
      start_date: string;
      end_date: string;
      phase_order: number;
    }>;
    is_public?: boolean;
    story_type_slug?: StoryTypeSlug;
    theme_color?: string;
  }) => void;
  isCreating: boolean;
  initialGoal?: string;
  initialTargetDays?: number;
  template?: EpicTemplate | null;
  showTemplatesFirst?: boolean;
  clarificationAnswers?: ClarificationAnswers;
  epicContext?: string;
  autoGenerateSuggestions?: boolean;
}

export function SmartEpicWizard({
  open,
  onOpenChange,
  onCreateEpic,
  isCreating,
  initialGoal = '',
  initialTargetDays,
  template,
  showTemplatesFirst = false,
  clarificationAnswers,
  epicContext,
  autoGenerateSuggestions = false,
}: SmartEpicWizardProps) {
  const hasAutoGeneratedRef = useRef(false);
  const [step, setStep] = useState<WizardStep>('goal');
  const [goalInput, setGoalInput] = useState(initialGoal);
  const [deadline, setDeadline] = useState<Date | undefined>(undefined);
  
  const { preferences, isAtEpicLimit } = useUserAIContext();
  const { trackInteraction } = useAIInteractionTracker();
  const { schedule, isLoading: isScheduleLoading, generateSchedule, adjustSchedule, toggleMilestone, reset: resetSchedule } = useJourneySchedule();
  
  const targetDays = useMemo(() => {
    if (deadline) {
      return Math.max(7, differenceInDays(deadline, new Date()));
    }
    if (initialTargetDays) return initialTargetDays;
    return preferences.epicDuration || 30;
  }, [deadline, initialTargetDays, preferences.epicDuration]);
  
  const [epicTitle, setEpicTitle] = useState('');
  const [epicDescription, setEpicDescription] = useState('');
  const [customHabits, setCustomHabits] = useState<EpicSuggestion[]>([]);
  const [storyType, setStoryType] = useState<StoryTypeSlug | null>(null);
  const [themeColor, setThemeColor] = useState(themeColors[0].value);
  const [selectedTemplate, setSelectedTemplate] = useState<EpicTemplate | null>(template || null);
  const { medium, success, light, tap } = useHapticFeedback();
  
  const { templates, incrementPopularity } = useEpicTemplates();
  const {
    suggestions,
    isLoading: isGenerating,
    error,
    generateSuggestions,
    toggleSuggestion,
    selectAll,
    deselectAll,
    getSelectedSuggestions,
    reset: resetSuggestions,
  } = useEpicSuggestions();

  const [interimText, setInterimText] = useState('');
  
  const {
    isRecording,
    isAutoStopping,
    startRecording,
    stopRecording,
  } = useVoiceInput({
    onInterimResult: (text) => setInterimText(text),
    onFinalResult: (text) => {
      setGoalInput((prev) => (prev ? prev + ' ' + text : text).trim());
      setInterimText('');
      success();
    },
    autoStopOnSilence: true,
    silenceTimeoutMs: 2000,
  });

  // Apply template when selected
  useEffect(() => {
    if (selectedTemplate && open) {
      setEpicTitle(selectedTemplate.name);
      setEpicDescription(selectedTemplate.description);
      setDeadline(addDays(new Date(), selectedTemplate.target_days));
      setThemeColor(selectedTemplate.theme_color || themeColors[0].value);
      
      const templateSuggestions: EpicSuggestion[] = selectedTemplate.habits.map((h, idx) => ({
        id: `template-${idx}`,
        type: 'habit' as const,
        title: h.title,
        description: '',
        difficulty: (h.difficulty || 'medium') as 'easy' | 'medium' | 'hard',
        frequency: (h.frequency === 'weekly' ? 'weekly' : h.frequency === 'custom' ? 'custom' : 'daily') as 'daily' | 'weekly' | 'custom',
        isSelected: true,
      }));
      setCustomHabits(templateSuggestions);
      setStep('story');
    }
  }, [selectedTemplate, open]);

  useEffect(() => {
    if (template && open) {
      setSelectedTemplate(template);
    }
  }, [template, open]);

  useEffect(() => {
    if (!open) {
      hasAutoGeneratedRef.current = false;
    }
  }, [open]);

  const selectedSuggestions = useMemo(() => getSelectedSuggestions(), [getSelectedSuggestions]);
  const selectedHabits = useMemo(
    () => {
      // Use schedule rituals if available, otherwise fall back to suggestions
      if (schedule?.rituals) {
        return schedule.rituals.map(r => ({
          id: r.id,
          title: r.title,
          description: r.description,
          type: 'habit' as const,
          difficulty: r.difficulty,
          frequency: r.frequency,
          isSelected: true,
        }));
      }
      return [...selectedSuggestions.filter((s) => s.type === 'habit'), ...customHabits];
    },
    [schedule, selectedSuggestions, customHabits]
  );
  const selectedMilestones = useMemo(
    () => schedule?.milestones || selectedSuggestions.filter((s) => s.type === 'milestone'),
    [schedule, selectedSuggestions]
  );

  const calculateXP = useMemo(() => targetDays * EPIC_XP_REWARDS.XP_PER_DAY, [targetDays]);

  const handleGenerateTimeline = useCallback(async () => {
    if (!goalInput.trim() || !deadline) return;
    tap();
    
    const deadlineStr = format(deadline, 'yyyy-MM-dd');
    await generateSchedule({
      goal: goalInput,
      deadline: deadlineStr,
      clarificationAnswers,
      epicContext,
    });
    
    setStep('timeline');
    success();
  }, [goalInput, deadline, clarificationAnswers, epicContext, generateSchedule, tap, success]);

  const handleAdjustSchedule = useCallback(async (feedback: string) => {
    if (!schedule || !deadline) return;
    
    await adjustSchedule({
      goal: goalInput,
      deadline: format(deadline, 'yyyy-MM-dd'),
      adjustmentRequest: feedback,
      previousSchedule: {
        phases: schedule.phases,
        milestones: schedule.milestones,
        rituals: schedule.rituals,
      },
    });
  }, [schedule, deadline, goalInput, adjustSchedule]);

  const handleProceedToSuggestions = useCallback(() => {
    if (!schedule) return;
    setStep('suggestions');
    medium();
  }, [schedule, medium]);

  const handleProceedToStory = useCallback(() => {
    if (!epicTitle) {
      setEpicTitle(goalInput);
    }
    setStep('story');
    medium();
  }, [epicTitle, goalInput, medium]);

  const handleProceedToReview = useCallback(() => {
    if (!storyType) return;
    setStep('review');
    medium();
  }, [storyType, medium]);

  const handleCreateEpic = useCallback(() => {
    if (selectedHabits.length === 0) return;

    const habits = selectedHabits.map((h) => ({
      title: h.title,
      difficulty: h.difficulty,
      frequency: h.frequency || 'daily',
      custom_days: [],
    }));

    // Include milestones with dates from schedule
    const milestones = schedule?.milestones.map(m => ({
      title: m.title,
      description: m.description,
      target_date: m.targetDate,
      milestone_percent: m.milestonePercent,
      is_postcard_milestone: m.isPostcardMilestone,
    }));

    // Include phases from schedule
    const phases = schedule?.phases.map(p => ({
      name: p.name,
      description: p.description,
      start_date: p.startDate,
      end_date: p.endDate,
      phase_order: p.phaseOrder,
    }));

    trackInteraction({
      interactionType: 'epic-creation',
      inputText: goalInput,
      aiResponse: { 
        totalSuggestions: suggestions?.length || 0,
        selectedHabits: selectedHabits.length,
        targetDays,
        storyType,
        hasSchedule: !!schedule,
      },
      userAction: 'accepted',
      detectedIntent: 'epic',
    });

    onCreateEpic({
      title: epicTitle || goalInput,
      description: epicDescription || undefined,
      target_days: targetDays,
      habits,
      milestones,
      phases,
      is_public: true,
      story_type_slug: storyType || undefined,
      theme_color: themeColor,
    });

    success();
  }, [selectedHabits, epicTitle, goalInput, epicDescription, targetDays, storyType, themeColor, schedule, onCreateEpic, success, trackInteraction, suggestions]);

  const handleBack = useCallback(() => {
    light();
    if (step === 'timeline') setStep('goal');
    else if (step === 'suggestions') setStep('timeline');
    else if (step === 'story') setStep('suggestions');
    else if (step === 'review') setStep('story');
  }, [step, light]);

  const handleClose = useCallback(() => {
    setStep('goal');
    setGoalInput(initialGoal);
    setDeadline(undefined);
    setEpicTitle('');
    setEpicDescription('');
    setCustomHabits([]);
    setStoryType(null);
    setThemeColor(themeColors[0].value);
    setSelectedTemplate(null);
    resetSuggestions();
    resetSchedule();
    onOpenChange(false);
  }, [onOpenChange, resetSuggestions, resetSchedule, initialGoal]);

  const handleVoiceToggle = useCallback(() => {
    if (isRecording) {
      stopRecording();
    } else {
      startRecording();
    }
    tap();
  }, [isRecording, startRecording, stopRecording, tap]);

  const steps: WizardStep[] = ['goal', 'timeline', 'suggestions', 'story', 'review'];
  const currentStepIndex = steps.indexOf(step);

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-lg max-h-[90vh] overflow-hidden flex flex-col p-0">
        <DialogHeader className="p-6 pb-4">
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-primary" />
            Smart Journey Wizard
          </DialogTitle>
          <DialogDescription>
            {step === 'goal' && 'Set your goal and deadline'}
            {step === 'timeline' && 'Review your AI-generated timeline'}
            {step === 'suggestions' && 'Confirm your rituals and milestones'}
            {step === 'story' && 'Choose your narrative adventure style'}
            {step === 'review' && 'Review and create your journey'}
          </DialogDescription>
        </DialogHeader>

        {isAtEpicLimit && (
          <div className="px-6 pb-2">
            <CapacityWarningBanner isAtEpicLimit={isAtEpicLimit} isLoading={false} />
          </div>
        )}

        {/* Progress indicator */}
        <div className="px-6 pb-4">
          <div className="flex items-center gap-2">
            {steps.map((s, i) => (
              <div key={s} className="flex items-center">
                <div
                  className={cn(
                    'w-8 h-8 rounded-full flex items-center justify-center text-sm font-medium transition-all',
                    step === s
                      ? 'bg-primary text-primary-foreground'
                      : currentStepIndex > i
                      ? 'bg-primary/20 text-primary'
                      : 'bg-muted text-muted-foreground'
                  )}
                >
                  {currentStepIndex > i ? <Check className="w-4 h-4" /> : i + 1}
                </div>
                {i < steps.length - 1 && (
                  <div className={cn('w-4 h-0.5 mx-1', currentStepIndex > i ? 'bg-primary' : 'bg-muted')} />
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Step Content */}
        <div className="flex-1 min-h-0 overflow-hidden">
          <AnimatePresence mode="wait">
            {/* Step 1: Goal & Deadline */}
            {step === 'goal' && (
              <motion.div
                key="goal"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="px-6 pb-6 space-y-4"
              >
                <div className="space-y-2">
                  <Label htmlFor="goal-input" className="text-base font-semibold">
                    What's your goal?
                  </Label>
                  <div className="relative">
                    <Textarea
                      id="goal-input"
                      placeholder="e.g., Pass the bar exam, Run a marathon, Learn Spanish"
                      value={isRecording ? goalInput + (interimText ? ' ' + interimText : '') : goalInput}
                      onChange={(e) => setGoalInput(e.target.value)}
                      rows={3}
                      className="pr-12 text-base"
                    />
                    <Button
                      size="icon"
                      variant={isRecording ? 'default' : 'ghost'}
                      className={cn(
                        'absolute right-2 top-2 h-8 w-8',
                        isRecording && 'animate-pulse bg-red-500 hover:bg-red-600'
                      )}
                      onClick={handleVoiceToggle}
                      disabled={isAutoStopping}
                    >
                      <Mic className="w-4 h-4" />
                    </Button>
                  </div>
                </div>

                {/* Deadline picker */}
                <div className="space-y-2">
                  <Label className="text-base font-semibold flex items-center gap-2">
                    <Calendar className="w-4 h-4" />
                    When do you need to achieve this?
                  </Label>
                  <DeadlinePicker value={deadline} onChange={setDeadline} />
                </div>

                {/* Generate button */}
                <Button
                  onClick={handleGenerateTimeline}
                  disabled={!goalInput.trim() || !deadline || isScheduleLoading}
                  className="w-full h-12 text-base"
                  size="lg"
                >
                  {isScheduleLoading ? (
                    <>
                      <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                      Creating your plan...
                    </>
                  ) : (
                    <>
                      <Wand2 className="w-5 h-5 mr-2" />
                      Generate Smart Timeline
                    </>
                  )}
                </Button>

                {error && (
                  <p className="text-sm text-destructive text-center">{error}</p>
                )}
              </motion.div>
            )}

            {/* Step 2: Timeline Review */}
            {step === 'timeline' && schedule && (
              <motion.div
                key="timeline"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="flex flex-col h-full min-h-0"
              >
                <ScrollArea className="flex-1 px-4">
                  <div className="space-y-4 pb-4">
                    <TimelineView
                      feasibilityAssessment={schedule.feasibilityAssessment}
                      phases={schedule.phases}
                      milestones={schedule.milestones}
                      rituals={schedule.rituals}
                      weeklyHoursEstimate={schedule.weeklyHoursEstimate}
                      deadline={format(deadline!, 'yyyy-MM-dd')}
                      onMilestoneToggle={toggleMilestone}
                    />

                    {/* Adjustment input */}
                    <div className="pt-4 border-t">
                      <AdjustmentInput onSubmit={handleAdjustSchedule} isLoading={isScheduleLoading} />
                    </div>

                    {/* Actions */}
                    <div className="space-y-3 pt-2">
                      <Button onClick={handleProceedToSuggestions} className="w-full">
                        Continue with this plan
                        <ChevronRight className="w-4 h-4 ml-1" />
                      </Button>
                      <Button variant="ghost" onClick={handleBack} className="w-full">
                        <ChevronLeft className="w-4 h-4 mr-1" />
                        Change goal or deadline
                      </Button>
                    </div>
                  </div>
                </ScrollArea>
              </motion.div>
            )}

            {/* Step 3: Suggestions confirmation */}
            {step === 'suggestions' && (
              <motion.div
                key="suggestions"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="flex flex-col h-full"
              >
                <ScrollArea className="flex-1 px-6">
                  <div className="space-y-4 pb-4">
                    {/* Rituals */}
                    <div className="space-y-2">
                      <div className="flex items-center gap-2 text-sm font-medium">
                        <Repeat className="w-4 h-4" />
                        Daily & Weekly Rituals ({selectedHabits.length})
                      </div>
                      {selectedHabits.map((h) => (
                        <div key={h.id} className="p-3 bg-secondary/50 rounded-lg">
                          <div className="flex items-center justify-between">
                            <span className="font-medium">{h.title}</span>
                            <Badge variant="outline">{h.frequency}</Badge>
                          </div>
                          {h.description && (
                            <p className="text-sm text-muted-foreground mt-1">{h.description}</p>
                          )}
                        </div>
                      ))}
                    </div>

                    {/* Milestones */}
                    <div className="space-y-2">
                      <div className="flex items-center gap-2 text-sm font-medium">
                        <Flag className="w-4 h-4" />
                        Milestones ({selectedMilestones.length})
                      </div>
                      {selectedMilestones.map((m: any) => (
                        <div key={m.id} className="p-3 bg-amber-500/10 rounded-lg">
                          <div className="flex items-center justify-between">
                            <span className="font-medium">{m.title}</span>
                            <Badge variant="outline">
                              {m.targetDate ? format(parseISO(m.targetDate), 'MMM d') : `Week ${m.suggestedWeek}`}
                            </Badge>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </ScrollArea>

                <div className="p-6 pt-4 border-t bg-background space-y-3">
                  <Button onClick={handleProceedToStory} className="w-full">
                    Continue to story selection
                    <ChevronRight className="w-4 h-4 ml-1" />
                  </Button>
                  <Button variant="ghost" onClick={handleBack} className="w-full">
                    <ChevronLeft className="w-4 h-4 mr-1" />
                    Back to Timeline
                  </Button>
                </div>
              </motion.div>
            )}

            {/* Step 4: Story & Theme */}
            {step === 'story' && (
              <StoryStep
                storyType={storyType}
                themeColor={themeColor}
                targetDays={targetDays}
                onStoryTypeChange={setStoryType}
                onThemeColorChange={setThemeColor}
                onContinue={handleProceedToReview}
                onBack={handleBack}
              />
            )}

            {/* Step 5: Review */}
            {step === 'review' && (
              <motion.div
                key="review"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="flex flex-col h-full"
              >
                <ScrollArea className="flex-1 px-6">
                  <div className="space-y-4 pb-4">
                    <div className="space-y-2">
                      <Label htmlFor="epic-title">Journey Name</Label>
                      <Input
                        id="epic-title"
                        value={epicTitle}
                        onChange={(e) => setEpicTitle(e.target.value)}
                        placeholder="Name your journey"
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="epic-desc">Description (optional)</Label>
                      <Textarea
                        id="epic-desc"
                        value={epicDescription}
                        onChange={(e) => setEpicDescription(e.target.value)}
                        placeholder="Add more details"
                        rows={2}
                      />
                    </div>

                    <div className="p-4 bg-gradient-to-r from-primary/10 to-purple-500/10 rounded-xl border border-primary/20">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <Zap className="w-5 h-5 text-primary" />
                          <span className="font-medium">Completion Reward</span>
                        </div>
                        <span className="text-xl font-bold text-primary">+{calculateXP} XP</span>
                      </div>
                      <p className="text-xs text-muted-foreground mt-1">
                        {targetDays} days • {selectedHabits.length} rituals • {selectedMilestones.length} milestones
                      </p>
                    </div>
                  </div>
                </ScrollArea>

                <div className="p-6 pt-4 border-t bg-background space-y-3">
                  <Button
                    onClick={handleCreateEpic}
                    disabled={isCreating || selectedHabits.length === 0}
                    className="w-full bg-gradient-to-r from-primary to-purple-600"
                  >
                    {isCreating ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        Creating...
                      </>
                    ) : (
                      <>
                        <Target className="w-4 h-4 mr-2" />
                        Create Journey
                      </>
                    )}
                  </Button>
                  <Button variant="ghost" onClick={handleBack} className="w-full">
                    <ChevronLeft className="w-4 h-4 mr-1" />
                    Back
                  </Button>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </DialogContent>
    </Dialog>
  );
}
