-- Create storage bucket for evolution cards images
-- This bucket stores companion evolution card images generated by the system

INSERT INTO storage.buckets (id, name, public)
VALUES ('evolution-cards', 'evolution-cards', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policies for evolution-cards bucket
-- Public can view evolution card images
CREATE POLICY "Public can view evolution cards"
ON storage.objects FOR SELECT
USING (bucket_id = 'evolution-cards');

-- Authenticated users can upload their own evolution card images
CREATE POLICY "Users can upload own evolution cards"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'evolution-cards' 
  AND auth.role() = 'authenticated'
);

-- Service role can manage all evolution card images (for edge functions)
CREATE POLICY "Service role can manage evolution cards"
ON storage.objects FOR ALL
USING (bucket_id = 'evolution-cards' AND auth.role() = 'service_role');

