-- Bulk insert 200+ curated real quotes with categories, emotional triggers, and intensity levels
-- Clear existing quotes first to avoid duplicates (optional - comment out if you want to keep existing)
-- TRUNCATE TABLE public.quotes;

INSERT INTO public.quotes (text, author, category, emotional_triggers, intensity, is_premium) VALUES
-- DISCIPLINE quotes
('Discipline is the bridge between goals and accomplishment.', 'Jim Rohn', 'discipline', ARRAY['Needing Discipline', 'Avoiding Action'], 'intense', false),
('We do today what they won''t, so tomorrow we can accomplish what they can''t.', 'Dwayne Johnson', 'discipline', ARRAY['Needing Discipline', 'Motivated & Ready'], 'intense', false),
('Discipline is choosing between what you want now and what you want most.', 'Abraham Lincoln', 'discipline', ARRAY['Needing Discipline', 'Avoiding Action'], 'moderate', false),
('The pain of discipline is far less than the pain of regret.', 'Sarah Bombell', 'discipline', ARRAY['Needing Discipline', 'Avoiding Action'], 'intense', false),
('Self-discipline is the ability to make yourself do what you should do, when you should do it, whether you feel like it or not.', 'Elbert Hubbard', 'discipline', ARRAY['Needing Discipline', 'Unmotivated'], 'moderate', false),
('We are what we repeatedly do. Excellence, then, is not an act, but a habit.', 'Aristotle', 'discipline', ARRAY['Needing Discipline'], 'moderate', false),
('Success is nothing more than a few simple disciplines, practiced every day.', 'Jim Rohn', 'discipline', ARRAY['Needing Discipline', 'Feeling Stuck'], 'gentle', false),
('Discipline is the soul of an army. It makes small numbers formidable.', 'George Washington', 'discipline', ARRAY['Needing Discipline'], 'intense', false),
('With self-discipline, most anything is possible.', 'Theodore Roosevelt', 'discipline', ARRAY['Self-Doubt', 'Needing Discipline'], 'gentle', false),
('The first and greatest victory is to conquer yourself.', 'Plato', 'discipline', ARRAY['Needing Discipline', 'Self-Doubt'], 'intense', false),
('Do not bite at the bait of pleasure till you know there is no hook beneath it.', 'Thomas Jefferson', 'discipline', ARRAY['Avoiding Action', 'Needing Discipline'], 'moderate', false),
('Rule your mind or it will rule you.', 'Horace', 'discipline', ARRAY['Anxious & Overthinking', 'Needing Discipline'], 'intense', false),
('He who conquers himself is the mightiest warrior.', 'Confucius', 'discipline', ARRAY['Needing Discipline', 'Self-Doubt'], 'intense', false),

-- CONFIDENCE quotes
('Believe you can and you''re halfway there.', 'Theodore Roosevelt', 'confidence', ARRAY['Self-Doubt', 'Anxious & Overthinking'], 'gentle', false),
('Confidence comes not from always being right but from not fearing to be wrong.', 'Peter T. McIntyre', 'confidence', ARRAY['Self-Doubt', 'Anxious & Overthinking'], 'moderate', false),
('You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face.', 'Eleanor Roosevelt', 'confidence', ARRAY['Self-Doubt', 'Anxious & Overthinking'], 'moderate', false),
('With confidence, you have won before you have started.', 'Marcus Garvey', 'confidence', ARRAY['Self-Doubt', 'Motivated & Ready'], 'intense', false),
('No one can make you feel inferior without your consent.', 'Eleanor Roosevelt', 'confidence', ARRAY['Self-Doubt', 'Emotionally Hurt'], 'intense', false),
('You are braver than you believe, stronger than you seem, and smarter than you think.', 'A.A. Milne', 'confidence', ARRAY['Self-Doubt', 'Heavy or Low'], 'gentle', false),
('Act as if what you do makes a difference. It does.', 'William James', 'confidence', ARRAY['Self-Doubt', 'Unmotivated'], 'moderate', false),
('To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.', 'Ralph Waldo Emerson', 'confidence', ARRAY['Self-Doubt', 'Feeling Stuck'], 'moderate', false),
('Trust yourself. You know more than you think you do.', 'Benjamin Spock', 'confidence', ARRAY['Self-Doubt', 'Anxious & Overthinking'], 'gentle', false),
('The moment you doubt whether you can fly, you cease forever to be able to do it.', 'J.M. Barrie', 'confidence', ARRAY['Self-Doubt'], 'moderate', false),
('Low self-confidence isn''t a life sentence. Self-confidence can be learned, practiced, and mastered.', 'Barrie Davenport', 'confidence', ARRAY['Self-Doubt', 'Feeling Stuck'], 'gentle', false),
('Because one believes in oneself, one doesn''t try to convince others.', 'Lao Tzu', 'confidence', ARRAY['Self-Doubt'], 'moderate', false),
('I am not afraid of storms, for I am learning how to sail my ship.', 'Louisa May Alcott', 'confidence', ARRAY['Anxious & Overthinking', 'In Transition'], 'gentle', false),

-- MINDSET quotes
('Whether you think you can or you think you can''t, you''re right.', 'Henry Ford', 'mindset', ARRAY['Self-Doubt', 'Avoiding Action'], 'intense', false),
('The mind is everything. What you think you become.', 'Buddha', 'mindset', ARRAY['Self-Doubt', 'Feeling Stuck'], 'moderate', false),
('Change your thoughts and you change your world.', 'Norman Vincent Peale', 'mindset', ARRAY['Heavy or Low', 'In Transition'], 'gentle', false),
('Your limitation—it''s only your imagination.', 'Unknown', 'mindset', ARRAY['Feeling Stuck', 'Self-Doubt'], 'intense', false),
('The only limits that exist are the ones in your own mind.', 'Unknown', 'mindset', ARRAY['Self-Doubt', 'Feeling Stuck'], 'moderate', false),
('A positive mindset brings positive things.', 'Unknown', 'mindset', ARRAY['Heavy or Low', 'Unmotivated'], 'gentle', false),
('Once you replace negative thoughts with positive ones, you''ll start having positive results.', 'Willie Nelson', 'mindset', ARRAY['Heavy or Low', 'Self-Doubt'], 'moderate', false),
('The only person you are destined to become is the person you decide to be.', 'Ralph Waldo Emerson', 'mindset', ARRAY['Feeling Stuck', 'In Transition'], 'moderate', false),
('I am not a product of my circumstances. I am a product of my decisions.', 'Stephen Covey', 'mindset', ARRAY['Feeling Stuck', 'Emotionally Hurt'], 'intense', false),
('The greatest discovery of all time is that a person can change their future by merely changing their attitude.', 'Oprah Winfrey', 'mindset', ARRAY['Feeling Stuck', 'Heavy or Low'], 'moderate', false),
('What lies behind us and what lies before us are tiny matters compared to what lies within us.', 'Ralph Waldo Emerson', 'mindset', ARRAY['Heavy or Low', 'Self-Doubt'], 'gentle', false),
('Everything you''ve ever wanted is on the other side of fear.', 'George Addair', 'mindset', ARRAY['Anxious & Overthinking', 'Self-Doubt'], 'intense', false),
('The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.', 'Winston Churchill', 'mindset', ARRAY['Heavy or Low', 'Feeling Stuck'], 'moderate', false),

-- RESILIENCE quotes
('Fall seven times and stand up eight.', 'Japanese Proverb', 'resilience', ARRAY['Emotionally Hurt', 'Frustrated', 'Heavy or Low'], 'moderate', false),
('The greatest glory in living lies not in never falling, but in rising every time we fall.', 'Nelson Mandela', 'resilience', ARRAY['Emotionally Hurt', 'Frustrated'], 'moderate', false),
('It does not matter how slowly you go as long as you do not stop.', 'Confucius', 'resilience', ARRAY['Exhausted', 'Unmotivated'], 'gentle', false),
('Strength doesn''t come from what you can do. It comes from overcoming the things you once thought you couldn''t.', 'Rikki Rogers', 'resilience', ARRAY['Self-Doubt', 'Motivated & Ready'], 'moderate', false),
('Rock bottom became the solid foundation on which I rebuilt my life.', 'J.K. Rowling', 'resilience', ARRAY['Heavy or Low', 'In Transition'], 'moderate', false),
('Out of suffering have emerged the strongest souls; the most massive characters are seared with scars.', 'Khalil Gibran', 'resilience', ARRAY['Emotionally Hurt', 'Heavy or Low'], 'intense', false),
('The human capacity for burden is like bamboo—far more flexible than you''d ever believe at first glance.', 'Jodi Picoult', 'resilience', ARRAY['Exhausted', 'Heavy or Low'], 'gentle', false),
('Persistence and resilience only come from having been given the chance to work through difficult problems.', 'Gever Tulley', 'resilience', ARRAY['Frustrated', 'Feeling Stuck'], 'moderate', false),
('You may have to fight a battle more than once to win it.', 'Margaret Thatcher', 'resilience', ARRAY['Frustrated', 'Avoiding Action'], 'intense', false),
('Life doesn''t get easier or more forgiving, we get stronger and more resilient.', 'Steve Maraboli', 'resilience', ARRAY['Exhausted', 'Heavy or Low'], 'moderate', false),
('I can be changed by what happens to me. But I refuse to be reduced by it.', 'Maya Angelou', 'resilience', ARRAY['Emotionally Hurt', 'In Transition'], 'intense', false),
('When we learn how to become resilient, we learn how to embrace the beautifully broad spectrum of the human experience.', 'Jaeda Dewalt', 'resilience', ARRAY['Heavy or Low', 'In Transition'], 'gentle', false),
('Tough times never last, but tough people do.', 'Robert H. Schuller', 'resilience', ARRAY['Heavy or Low', 'Exhausted'], 'moderate', false),

-- FOCUS quotes
('The successful warrior is the average man, with laser-like focus.', 'Bruce Lee', 'focus', ARRAY['Anxious & Overthinking', 'Avoiding Action'], 'intense', false),
('Concentrate all your thoughts upon the work in hand. The sun''s rays do not burn until brought to a focus.', 'Alexander Graham Bell', 'focus', ARRAY['Anxious & Overthinking'], 'moderate', false),
('Focus on being productive instead of busy.', 'Tim Ferriss', 'focus', ARRAY['Anxious & Overthinking', 'Avoiding Action'], 'moderate', false),
('Where focus goes, energy flows.', 'Tony Robbins', 'focus', ARRAY['Anxious & Overthinking', 'Unmotivated'], 'moderate', false),
('The key to success is to focus our conscious mind on things we desire not things we fear.', 'Brian Tracy', 'focus', ARRAY['Anxious & Overthinking', 'Self-Doubt'], 'moderate', false),
('It''s not that I''m so smart, it''s just that I stay with problems longer.', 'Albert Einstein', 'focus', ARRAY['Frustrated', 'Feeling Stuck'], 'gentle', false),
('Concentration and mental toughness are the margins of victory.', 'Bill Russell', 'focus', ARRAY['Needing Discipline', 'Motivated & Ready'], 'intense', false),
('Focus is a matter of deciding what things you''re not going to do.', 'John Carmack', 'focus', ARRAY['Anxious & Overthinking'], 'moderate', false),
('The secret of change is to focus all of your energy not on fighting the old, but on building the new.', 'Socrates', 'focus', ARRAY['In Transition', 'Feeling Stuck'], 'moderate', false),
('Lack of direction, not lack of time, is the problem. We all have twenty-four hour days.', 'Zig Ziglar', 'focus', ARRAY['Anxious & Overthinking', 'Avoiding Action'], 'moderate', false),
('It''s not always that we need to do more but rather that we need to focus on less.', 'Nathan W. Morris', 'focus', ARRAY['Exhausted', 'Anxious & Overthinking'], 'gentle', false),
('You can''t depend on your eyes when your imagination is out of focus.', 'Mark Twain', 'focus', ARRAY['Anxious & Overthinking'], 'gentle', false),

-- COURAGE quotes
('Courage is not the absence of fear, but rather the judgment that something else is more important than fear.', 'Ambrose Redmoon', 'courage', ARRAY['Anxious & Overthinking', 'Avoiding Action'], 'moderate', false),
('You gain strength, courage and confidence by every experience in which you really stop to look fear in the face.', 'Eleanor Roosevelt', 'courage', ARRAY['Anxious & Overthinking', 'Self-Doubt'], 'moderate', false),
('Life shrinks or expands in proportion to one''s courage.', 'Anaïs Nin', 'courage', ARRAY['Avoiding Action', 'Self-Doubt'], 'moderate', false),
('Courage is resistance to fear, mastery of fear, not absence of fear.', 'Mark Twain', 'courage', ARRAY['Anxious & Overthinking'], 'moderate', false),
('It takes courage to grow up and become who you really are.', 'E.E. Cummings', 'courage', ARRAY['In Transition', 'Self-Doubt'], 'gentle', false),
('Have the courage to follow your heart and intuition.', 'Steve Jobs', 'courage', ARRAY['Self-Doubt', 'In Transition'], 'moderate', false),
('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Winston Churchill', 'courage', ARRAY['Frustrated', 'Emotionally Hurt'], 'moderate', false),
('Courage is the most important of all the virtues because without courage, you can''t practice any other virtue consistently.', 'Maya Angelou', 'courage', ARRAY['Avoiding Action', 'Self-Doubt'], 'moderate', false),
('One isn''t necessarily born with courage, but one is born with potential.', 'Maya Angelou', 'courage', ARRAY['Self-Doubt'], 'gentle', false),
('Fortune favors the brave.', 'Virgil', 'courage', ARRAY['Avoiding Action', 'Motivated & Ready'], 'intense', false),
('Courage doesn''t always roar. Sometimes courage is the quiet voice at the end of the day saying, I will try again tomorrow.', 'Mary Anne Radmacher', 'courage', ARRAY['Exhausted', 'Heavy or Low'], 'gentle', false),

-- GROWTH quotes
('The only way to do great work is to love what you do.', 'Steve Jobs', 'growth', ARRAY['Unmotivated', 'Feeling Stuck'], 'moderate', false),
('Don''t watch the clock; do what it does. Keep going.', 'Sam Levenson', 'growth', ARRAY['Exhausted', 'Avoiding Action'], 'moderate', false),
('The future belongs to those who believe in the beauty of their dreams.', 'Eleanor Roosevelt', 'growth', ARRAY['Self-Doubt', 'In Transition'], 'gentle', false),
('The best time to plant a tree was 20 years ago. The second best time is now.', 'Chinese Proverb', 'growth', ARRAY['In Transition', 'Feeling Stuck'], 'gentle', false),
('Growth is never by mere chance; it is the result of forces working together.', 'James Cash Penney', 'growth', ARRAY['Feeling Stuck', 'Unmotivated'], 'moderate', false),
('There is no growth without change, no change without fear or loss, and no loss without pain.', 'Rick Warren', 'growth', ARRAY['In Transition', 'Emotionally Hurt'], 'moderate', false),
('Be not afraid of growing slowly; be afraid only of standing still.', 'Chinese Proverb', 'growth', ARRAY['Feeling Stuck', 'Self-Doubt'], 'gentle', false),
('The only impossible journey is the one you never begin.', 'Tony Robbins', 'growth', ARRAY['Feeling Stuck', 'In Transition'], 'moderate', false),
('What we fear of doing most is usually what we most need to do.', 'Ralph Waldo Emerson', 'growth', ARRAY['Avoiding Action', 'Anxious & Overthinking'], 'intense', false),
('Personal growth is not a matter of learning new information but of unlearning old limits.', 'Alan Cohen', 'growth', ARRAY['Feeling Stuck', 'Self-Doubt'], 'moderate', false),
('Do something today that your future self will thank you for.', 'Sean Patrick Flanery', 'growth', ARRAY['Avoiding Action', 'Motivated & Ready'], 'gentle', false),
('Small daily improvements over time lead to stunning results.', 'Robin Sharma', 'growth', ARRAY['Exhausted', 'Needing Discipline'], 'gentle', false),

-- STOICISM quotes
('You have power over your mind - not outside events. Realize this, and you will find strength.', 'Marcus Aurelius', 'stoicism', ARRAY['Anxious & Overthinking', 'Frustrated'], 'moderate', false),
('The happiness of your life depends upon the quality of your thoughts.', 'Marcus Aurelius', 'stoicism', ARRAY['Heavy or Low', 'Anxious & Overthinking'], 'moderate', false),
('Waste no more time arguing about what a good man should be. Be one.', 'Marcus Aurelius', 'stoicism', ARRAY['Avoiding Action', 'Needing Discipline'], 'intense', false),
('He who fears death will never do anything worthy of a living man.', 'Seneca', 'stoicism', ARRAY['Anxious & Overthinking', 'Avoiding Action'], 'intense', false),
('We suffer more often in imagination than in reality.', 'Seneca', 'stoicism', ARRAY['Anxious & Overthinking'], 'moderate', false),
('It is not the man who has too little, but the man who craves more, that is poor.', 'Seneca', 'stoicism', ARRAY['Feeling Stuck', 'Frustrated'], 'moderate', false),
('Man is not worried by real problems so much as by his imagined anxieties about real problems.', 'Epictetus', 'stoicism', ARRAY['Anxious & Overthinking'], 'moderate', false),
('First say to yourself what you would be; and then do what you have to do.', 'Epictetus', 'stoicism', ARRAY['Needing Discipline', 'Avoiding Action'], 'moderate', false),
('It''s not what happens to you, but how you react to it that matters.', 'Epictetus', 'stoicism', ARRAY['Frustrated', 'Emotionally Hurt'], 'moderate', false),
('Difficulties strengthen the mind, as labor does the body.', 'Seneca', 'stoicism', ARRAY['Frustrated', 'Exhausted'], 'moderate', false),
('If it is not right, do not do it. If it is not true, do not say it.', 'Marcus Aurelius', 'stoicism', ARRAY['Needing Discipline'], 'gentle', false),
('The best revenge is not to be like your enemy.', 'Marcus Aurelius', 'stoicism', ARRAY['Emotionally Hurt', 'Frustrated'], 'moderate', false),
('Begin at once to live, and count each separate day as a separate life.', 'Seneca', 'stoicism', ARRAY['Motivated & Ready', 'In Transition'], 'gentle', false),

-- SELF_LOVE quotes
('You yourself, as much as anybody in the entire universe, deserve your love and affection.', 'Buddha', 'self_love', ARRAY['Heavy or Low', 'Self-Doubt'], 'gentle', false),
('To love oneself is the beginning of a lifelong romance.', 'Oscar Wilde', 'self_love', ARRAY['Self-Doubt', 'Heavy or Low'], 'gentle', false),
('Self-care is not selfish. You cannot serve from an empty vessel.', 'Eleanor Brownn', 'self_love', ARRAY['Exhausted', 'Heavy or Low'], 'gentle', false),
('Love yourself first and everything else falls into line.', 'Lucille Ball', 'self_love', ARRAY['Self-Doubt', 'Feeling Stuck'], 'gentle', false),
('Your relationship with yourself sets the tone for every other relationship you have.', 'Robert Holden', 'self_love', ARRAY['Self-Doubt', 'Emotionally Hurt'], 'moderate', false),
('Owning our story and loving ourselves through that process is the bravest thing that we will ever do.', 'Brené Brown', 'self_love', ARRAY['Heavy or Low', 'Emotionally Hurt'], 'moderate', false),
('You are enough just as you are.', 'Meghan Markle', 'self_love', ARRAY['Self-Doubt', 'Heavy or Low'], 'gentle', false),
('Talk to yourself like you would to someone you love.', 'Brené Brown', 'self_love', ARRAY['Self-Doubt', 'Heavy or Low'], 'gentle', false),
('The most powerful relationship you will ever have is the relationship with yourself.', 'Steve Maraboli', 'self_love', ARRAY['Self-Doubt'], 'moderate', false),
('You are worthy of the love you keep trying to give everyone else.', 'Unknown', 'self_love', ARRAY['Heavy or Low', 'Exhausted'], 'gentle', false),
('Self-love is not vanity. It is sanity.', 'Katrina Mayer', 'self_love', ARRAY['Self-Doubt'], 'gentle', false),
('Be gentle with yourself. You''re doing the best you can.', 'Unknown', 'self_love', ARRAY['Exhausted', 'Heavy or Low', 'Frustrated'], 'gentle', false),

-- HEALING quotes
('Healing doesn''t mean the damage never existed. It means the damage no longer controls our lives.', 'Akshay Dubey', 'healing', ARRAY['Emotionally Hurt', 'Heavy or Low'], 'moderate', false),
('The wound is the place where the Light enters you.', 'Rumi', 'healing', ARRAY['Emotionally Hurt', 'Heavy or Low'], 'gentle', false),
('Time doesn''t heal emotional pain, you need to learn how to let go.', 'Roy T. Bennett', 'healing', ARRAY['Emotionally Hurt'], 'moderate', false),
('Healing is not linear.', 'Unknown', 'healing', ARRAY['Frustrated', 'Heavy or Low'], 'gentle', false),
('You don''t have to control your thoughts. You just have to stop letting them control you.', 'Dan Millman', 'healing', ARRAY['Anxious & Overthinking', 'Heavy or Low'], 'moderate', false),
('The soul always knows what to do to heal itself. The challenge is to silence the mind.', 'Caroline Myss', 'healing', ARRAY['Anxious & Overthinking', 'Heavy or Low'], 'gentle', false),
('You are allowed to be both a masterpiece and a work in progress, simultaneously.', 'Sophia Bush', 'healing', ARRAY['Self-Doubt', 'In Transition'], 'gentle', false),
('Healing takes courage, and we all have courage, even if we have to dig a little to find it.', 'Tori Amos', 'healing', ARRAY['Heavy or Low', 'Exhausted'], 'gentle', false),
('One day at a time—this is enough. Do not look back and grieve over the past.', 'Ida Scott Taylor', 'healing', ARRAY['Emotionally Hurt', 'Heavy or Low'], 'gentle', false),
('You have been assigned this mountain to show others it can be moved.', 'Mel Robbins', 'healing', ARRAY['Heavy or Low', 'Emotionally Hurt'], 'moderate', false),
('What happens when people open their hearts? They get better.', 'Haruki Murakami', 'healing', ARRAY['Emotionally Hurt', 'Heavy or Low'], 'gentle', false),

-- GRATITUDE quotes
('Gratitude turns what we have into enough.', 'Anonymous', 'gratitude', ARRAY['Heavy or Low', 'Feeling Stuck'], 'gentle', false),
('When you are grateful, fear disappears and abundance appears.', 'Tony Robbins', 'gratitude', ARRAY['Anxious & Overthinking', 'Heavy or Low'], 'moderate', false),
('Gratitude is not only the greatest of virtues, but the parent of all others.', 'Cicero', 'gratitude', ARRAY['Heavy or Low'], 'gentle', false),
('The more grateful I am, the more beauty I see.', 'Mary Davis', 'gratitude', ARRAY['Heavy or Low', 'Unmotivated'], 'gentle', false),
('Acknowledging the good that you already have in your life is the foundation for all abundance.', 'Eckhart Tolle', 'gratitude', ARRAY['Heavy or Low', 'Feeling Stuck'], 'gentle', false),
('Gratitude makes sense of our past, brings peace for today, and creates a vision for tomorrow.', 'Melody Beattie', 'gratitude', ARRAY['Heavy or Low', 'In Transition'], 'gentle', false),
('Let gratitude be the pillow upon which you kneel to say your nightly prayer.', 'Maya Angelou', 'gratitude', ARRAY['Heavy or Low'], 'gentle', false),
('Gratitude is a powerful catalyst for happiness.', 'Amy Collette', 'gratitude', ARRAY['Heavy or Low', 'Unmotivated'], 'gentle', false),
('When we focus on our gratitude, the tide of disappointment goes out and the tide of love rushes in.', 'Kristin Armstrong', 'gratitude', ARRAY['Heavy or Low', 'Frustrated'], 'gentle', false),
('Enjoy the little things, for one day you may look back and realize they were the big things.', 'Robert Brault', 'gratitude', ARRAY['Heavy or Low', 'Feeling Stuck'], 'gentle', false),

-- MOTIVATION quotes
('Don''t let yesterday take up too much of today.', 'Will Rogers', 'motivation', ARRAY['Emotionally Hurt', 'Heavy or Low'], 'moderate', false),
('You learn more from failure than from success. Don''t let it stop you. Failure builds character.', 'Unknown', 'motivation', ARRAY['Frustrated', 'Emotionally Hurt'], 'moderate', false),
('If you are working on something that you really care about, you don''t have to be pushed. The vision pulls you.', 'Steve Jobs', 'motivation', ARRAY['Unmotivated', 'Motivated & Ready'], 'moderate', false),
('People who are crazy enough to think they can change the world, are the ones who do.', 'Rob Siltanen', 'motivation', ARRAY['Self-Doubt', 'Motivated & Ready'], 'intense', false),
('The way to get started is to quit talking and begin doing.', 'Walt Disney', 'motivation', ARRAY['Avoiding Action', 'Needing Discipline'], 'intense', false),
('Opportunities don''t happen. You create them.', 'Chris Grosser', 'motivation', ARRAY['Motivated & Ready', 'Needing Discipline'], 'intense', false),
('Don''t be afraid to give up the good to go for the great.', 'John D. Rockefeller', 'motivation', ARRAY['In Transition', 'Feeling Stuck'], 'moderate', false),
('The secret of getting ahead is getting started.', 'Mark Twain', 'motivation', ARRAY['Avoiding Action', 'Unmotivated'], 'moderate', false),
('I find that the harder I work, the more luck I seem to have.', 'Thomas Jefferson', 'motivation', ARRAY['Needing Discipline', 'Motivated & Ready'], 'moderate', false),
('Dream big and dare to fail.', 'Norman Vaughan', 'motivation', ARRAY['Self-Doubt', 'Motivated & Ready'], 'intense', false),
('I''d rather attempt to do something great and fail than to attempt to do nothing and succeed.', 'Robert H. Schuller', 'motivation', ARRAY['Avoiding Action', 'Self-Doubt'], 'intense', false),
('The biggest adventure you can take is to live the life of your dreams.', 'Oprah Winfrey', 'motivation', ARRAY['Motivated & Ready', 'In Transition'], 'moderate', false),
('If you can dream it, you can do it.', 'Walt Disney', 'motivation', ARRAY['Self-Doubt', 'Motivated & Ready'], 'gentle', false),

-- BREAKUPS quotes
('Hearts will never be practical until they are made unbreakable.', 'The Wizard of Oz', 'breakups', ARRAY['Emotionally Hurt', 'Heavy or Low'], 'gentle', false),
('The hottest love has the coldest end.', 'Socrates', 'breakups', ARRAY['Emotionally Hurt'], 'moderate', false),
('Pain makes you stronger, fear makes you braver, heartbreak makes you wiser.', 'Drake', 'breakups', ARRAY['Emotionally Hurt', 'Heavy or Low'], 'moderate', false),
('Sometimes good things fall apart so better things can fall together.', 'Marilyn Monroe', 'breakups', ARRAY['Emotionally Hurt', 'In Transition'], 'gentle', false),
('Don''t cry because it''s over, smile because it happened.', 'Dr. Seuss', 'breakups', ARRAY['Emotionally Hurt'], 'gentle', false),
('The cure for a broken heart is simple, my lady. A hot bath and a good night''s sleep.', 'Margaret George', 'breakups', ARRAY['Emotionally Hurt', 'Exhausted'], 'gentle', false),
('Turn your wounds into wisdom.', 'Oprah Winfrey', 'breakups', ARRAY['Emotionally Hurt', 'In Transition'], 'moderate', false),
('Never allow someone to be your priority while allowing yourself to be their option.', 'Mark Twain', 'breakups', ARRAY['Emotionally Hurt', 'Self-Doubt'], 'intense', false),
('You can''t start the next chapter of your life if you keep re-reading the last one.', 'Unknown', 'breakups', ARRAY['Emotionally Hurt', 'Feeling Stuck'], 'moderate', false),
('The only thing a person can ever really do is keep moving forward.', 'Haruki Murakami', 'breakups', ARRAY['Emotionally Hurt', 'Heavy or Low'], 'moderate', false),
('Letting go doesn''t mean giving up, but rather accepting that there are things that cannot be.', 'Unknown', 'breakups', ARRAY['Emotionally Hurt'], 'gentle', false),

-- INTUITION quotes
('Trust your instincts. Intuition doesn''t lie.', 'Oprah Winfrey', 'intuition', ARRAY['Anxious & Overthinking', 'Self-Doubt'], 'moderate', false),
('The intuitive mind is a sacred gift and the rational mind is a faithful servant.', 'Albert Einstein', 'intuition', ARRAY['Anxious & Overthinking'], 'moderate', false),
('Intuition is seeing with the soul.', 'Dean Koontz', 'intuition', ARRAY['Anxious & Overthinking', 'Self-Doubt'], 'gentle', false),
('Have the courage to follow your heart and intuition. They somehow already know what you truly want to become.', 'Steve Jobs', 'intuition', ARRAY['Self-Doubt', 'In Transition'], 'moderate', false),
('Your intuition is the most honest friend that you will ever have.', 'Doe Zantamata', 'intuition', ARRAY['Self-Doubt', 'Anxious & Overthinking'], 'gentle', false),
('Good instincts usually tell you what to do long before your head has figured it out.', 'Michael Burke', 'intuition', ARRAY['Anxious & Overthinking'], 'moderate', false),
('The only real valuable thing is intuition.', 'Albert Einstein', 'intuition', ARRAY['Anxious & Overthinking', 'Self-Doubt'], 'moderate', false),
('Intuition is a spiritual faculty and does not explain, but simply points the way.', 'Florence Scovel Shinn', 'intuition', ARRAY['Self-Doubt', 'In Transition'], 'gentle', false),
('Listen to your own voice, your own soul. Too many people listen to the noise of the world.', 'Leon Brown', 'intuition', ARRAY['Anxious & Overthinking', 'Self-Doubt'], 'moderate', false),
('Trust yourself. You''ve survived a lot, and you''ll survive whatever is coming.', 'Robert Tew', 'intuition', ARRAY['Anxious & Overthinking', 'Heavy or Low'], 'gentle', false),

-- PERFORMANCE quotes
('Excellence is not a skill. It is an attitude.', 'Ralph Marston', 'performance', ARRAY['Motivated & Ready', 'Needing Discipline'], 'moderate', false),
('The difference between ordinary and extraordinary is that little extra.', 'Jimmy Johnson', 'performance', ARRAY['Needing Discipline', 'Motivated & Ready'], 'moderate', false),
('Champions keep playing until they get it right.', 'Billie Jean King', 'performance', ARRAY['Frustrated', 'Needing Discipline'], 'intense', false),
('I''ve failed over and over and over again in my life. And that is why I succeed.', 'Michael Jordan', 'performance', ARRAY['Frustrated', 'Self-Doubt'], 'intense', false),
('It''s not whether you get knocked down, it''s whether you get up.', 'Vince Lombardi', 'performance', ARRAY['Frustrated', 'Heavy or Low'], 'intense', false),
('Don''t practice until you get it right. Practice until you can''t get it wrong.', 'Unknown', 'performance', ARRAY['Needing Discipline', 'Motivated & Ready'], 'intense', false),
('The harder the battle, the sweeter the victory.', 'Les Brown', 'performance', ARRAY['Frustrated', 'Motivated & Ready'], 'intense', false),
('What you lack in talent can be made up with desire, hustle and giving 110% all the time.', 'Don Zimmer', 'performance', ARRAY['Self-Doubt', 'Needing Discipline'], 'intense', false),
('You miss 100% of the shots you don''t take.', 'Wayne Gretzky', 'performance', ARRAY['Avoiding Action', 'Self-Doubt'], 'intense', false),
('There may be people that have more talent than you, but there''s no excuse for anyone to work harder than you do.', 'Derek Jeter', 'performance', ARRAY['Needing Discipline', 'Self-Doubt'], 'intense', false),
('Hard work beats talent when talent doesn''t work hard.', 'Tim Notke', 'performance', ARRAY['Needing Discipline', 'Self-Doubt'], 'intense', false),

-- SELF_RESPECT quotes
('Respect yourself enough to walk away from anything that no longer serves you, grows you, or makes you happy.', 'Robert Tew', 'self_respect', ARRAY['Emotionally Hurt', 'In Transition'], 'moderate', false),
('Never be bullied into silence. Never allow yourself to be made a victim.', 'Harvey Fierstein', 'self_respect', ARRAY['Emotionally Hurt', 'Self-Doubt'], 'intense', false),
('Self-respect is the fruit of discipline; the sense of dignity grows with the ability to say no to oneself.', 'Abraham Joshua Heschel', 'self_respect', ARRAY['Needing Discipline', 'Self-Doubt'], 'moderate', false),
('The way you treat yourself sets the standard for others.', 'Sonya Friedman', 'self_respect', ARRAY['Self-Doubt', 'Emotionally Hurt'], 'moderate', false),
('If you want to be respected by others, the great thing is to respect yourself.', 'Fyodor Dostoevsky', 'self_respect', ARRAY['Self-Doubt'], 'moderate', false),
('Don''t lower your standards for anyone or anything. Self-respect is everything.', 'Unknown', 'self_respect', ARRAY['Emotionally Hurt', 'Self-Doubt'], 'intense', false),
('Respect yourself and others will respect you.', 'Confucius', 'self_respect', ARRAY['Self-Doubt'], 'gentle', false),
('Your self-worth is determined by you. You don''t have to depend on someone telling you who you are.', 'Beyoncé', 'self_respect', ARRAY['Self-Doubt', 'Emotionally Hurt'], 'moderate', false),
('Never compromise your values for anyone or anything.', 'Unknown', 'self_respect', ARRAY['Emotionally Hurt', 'In Transition'], 'moderate', false),
('Self-respect permeates every aspect of your life.', 'Joe Clark', 'self_respect', ARRAY['Self-Doubt'], 'gentle', false),

-- MINDFULNESS quotes
('Be where you are, not where you think you should be.', 'Unknown', 'mindfulness', ARRAY['Anxious & Overthinking', 'Heavy or Low'], 'gentle', false),
('The present moment is filled with joy and happiness. If you are attentive, you will see it.', 'Thich Nhat Hanh', 'mindfulness', ARRAY['Anxious & Overthinking', 'Heavy or Low'], 'gentle', false),
('In today''s rush, we all think too much, seek too much, want too much and forget about the joy of just being.', 'Eckhart Tolle', 'mindfulness', ARRAY['Anxious & Overthinking', 'Exhausted'], 'gentle', false),
('Mindfulness is a way of befriending ourselves and our experience.', 'Jon Kabat-Zinn', 'mindfulness', ARRAY['Anxious & Overthinking'], 'gentle', false),
('The little things? The little moments? They aren''t little.', 'Jon Kabat-Zinn', 'mindfulness', ARRAY['Heavy or Low'], 'gentle', false),
('Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.', 'Thich Nhat Hanh', 'mindfulness', ARRAY['Anxious & Overthinking', 'Emotionally Hurt'], 'gentle', false),
('Almost everything will work again if you unplug it for a few minutes, including you.', 'Anne Lamott', 'mindfulness', ARRAY['Exhausted', 'Anxious & Overthinking'], 'gentle', false),
('Peace comes from within. Do not seek it without.', 'Buddha', 'mindfulness', ARRAY['Anxious & Overthinking', 'Heavy or Low'], 'gentle', false),
('You can''t stop the waves, but you can learn to surf.', 'Jon Kabat-Zinn', 'mindfulness', ARRAY['Anxious & Overthinking', 'Frustrated'], 'moderate', false),
('The mind is like water. When it''s turbulent, it''s difficult to see. When it''s calm, everything becomes clear.', 'Prasad Mahes', 'mindfulness', ARRAY['Anxious & Overthinking'], 'gentle', false),
('Wherever you are, be all there.', 'Jim Elliot', 'mindfulness', ARRAY['Anxious & Overthinking', 'Avoiding Action'], 'gentle', false),
('Respond; don''t react. Listen; don''t talk. Think; don''t assume.', 'Raji Lukkoor', 'mindfulness', ARRAY['Anxious & Overthinking', 'Frustrated'], 'moderate', false),

-- Additional WISDOM quotes
('The only true wisdom is in knowing you know nothing.', 'Socrates', 'wisdom', ARRAY['Self-Doubt', 'Feeling Stuck'], 'moderate', false),
('In the middle of difficulty lies opportunity.', 'Albert Einstein', 'wisdom', ARRAY['Frustrated', 'Heavy or Low'], 'moderate', false),
('The journey of a thousand miles begins with a single step.', 'Lao Tzu', 'wisdom', ARRAY['Avoiding Action', 'Feeling Stuck'], 'gentle', false),
('Knowing yourself is the beginning of all wisdom.', 'Aristotle', 'wisdom', ARRAY['Self-Doubt', 'In Transition'], 'moderate', false),
('The wise man does at once what the fool does finally.', 'Niccolo Machiavelli', 'wisdom', ARRAY['Avoiding Action', 'Needing Discipline'], 'moderate', false),
('By three methods we may learn wisdom: by reflection, which is noblest; by imitation, which is easiest; and by experience, which is the bitterest.', 'Confucius', 'wisdom', ARRAY['Feeling Stuck', 'In Transition'], 'moderate', false),
('The only thing we have to fear is fear itself.', 'Franklin D. Roosevelt', 'wisdom', ARRAY['Anxious & Overthinking', 'Avoiding Action'], 'intense', false),
('You must be the change you wish to see in the world.', 'Mahatma Gandhi', 'wisdom', ARRAY['In Transition', 'Motivated & Ready'], 'moderate', false),
('An investment in knowledge pays the best interest.', 'Benjamin Franklin', 'wisdom', ARRAY['Feeling Stuck', 'Motivated & Ready'], 'gentle', false),
('The greatest wealth is to live content with little.', 'Plato', 'wisdom', ARRAY['Heavy or Low', 'Feeling Stuck'], 'gentle', false)

ON CONFLICT (text) DO NOTHING;