-- Expand Graceward's reviewed formation catalog and add an auditable path for
-- constrained, personalized practices generated by the server.

BEGIN;

CREATE TABLE public.daily_formation_practice_catalog (
  practice_key text PRIMARY KEY,
  category text NOT NULL CHECK (category IN ('Mind', 'Body', 'Soul')),
  focus text NOT NULL CHECK (focus IN ('knowledge', 'exercise', 'nutrition', 'scripture', 'faith')),
  CONSTRAINT daily_formation_practice_catalog_pillar_focus_check CHECK (
    (category = 'Mind' AND focus = 'knowledge')
    OR (category = 'Body' AND focus IN ('exercise', 'nutrition'))
    OR (category = 'Soul' AND focus IN ('scripture', 'faith'))
  )
);

ALTER TABLE public.daily_formation_practice_catalog ENABLE ROW LEVEL SECURITY;

INSERT INTO public.daily_formation_practice_catalog (practice_key, category, focus)
SELECT practice_key, 'Mind', 'knowledge'
FROM unnest(ARRAY[
  'formation-02', 'formation-05', 'formation-09', 'formation-12',
  'formation-16', 'formation-19', 'formation-23', 'formation-26'
]::text[]) AS practice_key;

INSERT INTO public.daily_formation_practice_catalog (practice_key, category, focus)
SELECT format('formation-%s', lpad(practice_number::text, 2, '0')), 'Mind', 'knowledge'
FROM generate_series(29, 50) AS practice_number;

INSERT INTO public.daily_formation_practice_catalog (practice_key, category, focus)
SELECT practice_key, 'Body', 'exercise'
FROM unnest(ARRAY[
  'formation-03', 'formation-07', 'formation-14', 'formation-17', 'formation-24'
]::text[]) AS practice_key;

INSERT INTO public.daily_formation_practice_catalog (practice_key, category, focus)
SELECT format('formation-%s', lpad(practice_number::text, 2, '0')), 'Body', 'exercise'
FROM generate_series(51, 60) AS practice_number;

INSERT INTO public.daily_formation_practice_catalog (practice_key, category, focus)
SELECT practice_key, 'Body', 'nutrition'
FROM unnest(ARRAY['formation-10', 'formation-21', 'formation-28']::text[]) AS practice_key;

INSERT INTO public.daily_formation_practice_catalog (practice_key, category, focus)
SELECT format('formation-%s', lpad(practice_number::text, 2, '0')), 'Body', 'nutrition'
FROM generate_series(61, 72) AS practice_number;

INSERT INTO public.daily_formation_practice_catalog (practice_key, category, focus)
SELECT practice_key, 'Soul', 'scripture'
FROM unnest(ARRAY[
  'formation-04', 'formation-08', 'formation-13', 'formation-18', 'formation-25',
  'formation-73', 'formation-74', 'formation-75', 'formation-76', 'formation-77',
  'formation-78', 'formation-88'
]::text[]) AS practice_key;

INSERT INTO public.daily_formation_practice_catalog (practice_key, category, focus)
SELECT practice_key, 'Soul', 'faith'
FROM unnest(ARRAY[
  'formation-01', 'formation-06', 'formation-11', 'formation-15',
  'formation-20', 'formation-22', 'formation-27',
  'formation-79', 'formation-80', 'formation-81', 'formation-82',
  'formation-83', 'formation-84', 'formation-85', 'formation-86',
  'formation-87', 'formation-89', 'formation-90'
]::text[]) AS practice_key;

ALTER TABLE public.daily_formation_assignments
  ADD COLUMN practice_source text NOT NULL DEFAULT 'reviewed',
  ADD COLUMN focus text,
  ADD COLUMN scripture_reference text,
  ADD COLUMN generation_model text,
  ADD COLUMN generation_prompt_version text;

UPDATE public.daily_formation_assignments AS assignment
SET
  practice_source = 'reviewed',
  focus = catalog.focus
FROM public.daily_formation_practice_catalog AS catalog
WHERE catalog.practice_key = assignment.practice_key;

ALTER TABLE public.daily_formation_assignments
  ALTER COLUMN focus SET NOT NULL,
  DROP CONSTRAINT IF EXISTS daily_formation_assignments_practice_key_check,
  DROP CONSTRAINT IF EXISTS daily_formation_assignments_practice_category_check,
  ADD CONSTRAINT daily_formation_assignments_practice_key_check CHECK (
    practice_key ~ '^formation-[0-9]{2}$'
    OR practice_key ~ '^generated-[a-f0-9]{24}$'
  ),
  ADD CONSTRAINT daily_formation_assignments_source_check CHECK (
    practice_source IN ('reviewed', 'generated')
    AND (
      (practice_source = 'reviewed' AND practice_key ~ '^formation-[0-9]{2}$')
      OR (practice_source = 'generated' AND practice_key ~ '^generated-[a-f0-9]{24}$')
    )
  ),
  ADD CONSTRAINT daily_formation_assignments_focus_check CHECK (
    (category = 'Mind' AND focus = 'knowledge')
    OR (category = 'Body' AND focus IN ('exercise', 'nutrition'))
    OR (category = 'Soul' AND focus IN ('scripture', 'faith'))
  ),
  ADD CONSTRAINT daily_formation_assignments_generation_metadata_check CHECK (
    (practice_source = 'reviewed' AND generation_model IS NULL AND generation_prompt_version IS NULL)
    OR (practice_source = 'generated' AND generation_model IS NOT NULL AND generation_prompt_version IS NOT NULL)
  );

CREATE INDEX daily_formation_assignments_user_category_history_idx
  ON public.daily_formation_assignments (user_id, category, practice_date DESC);

CREATE OR REPLACE FUNCTION public.prepare_daily_formation_practice(
  p_practice_date date,
  p_practice_key text,
  p_category text,
  p_title text,
  p_action text,
  p_benefit text,
  p_minutes integer,
  p_selection_reason text DEFAULT 'Prepared for today'
)
RETURNS TABLE (
  assignment_id uuid,
  practice_date date,
  practice_key text,
  category text,
  title text,
  action text,
  benefit text,
  minutes integer,
  xp_reward integer,
  selection_reason text,
  task_id uuid,
  completed_at timestamptz,
  total_xp integer,
  practices_completed integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_user_id uuid := auth.uid();
  v_assignment public.daily_formation_assignments%ROWTYPE;
  v_catalog public.daily_formation_practice_catalog%ROWTYPE;
  v_task_id uuid;
  v_task_category text;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '42501';
  END IF;

  IF p_practice_date IS NULL
    OR p_practice_date < current_date - 1
    OR p_practice_date > current_date + 1 THEN
    RAISE EXCEPTION 'Practice date must be the user''s current local day' USING ERRCODE = '22023';
  END IF;

  SELECT catalog.* INTO v_catalog
  FROM public.daily_formation_practice_catalog AS catalog
  WHERE catalog.practice_key = p_practice_key;

  IF NOT FOUND OR v_catalog.category <> p_category THEN
    RAISE EXCEPTION 'Formation practice does not belong to the requested category' USING ERRCODE = '22023';
  END IF;
  IF p_minutes IS NULL OR p_minutes NOT BETWEEN 1 AND 15 THEN
    RAISE EXCEPTION 'Practice duration is invalid' USING ERRCODE = '22023';
  END IF;
  IF length(btrim(COALESCE(p_title, ''))) NOT BETWEEN 1 AND 120
    OR length(btrim(COALESCE(p_action, ''))) NOT BETWEEN 1 AND 600
    OR length(btrim(COALESCE(p_benefit, ''))) NOT BETWEEN 1 AND 600 THEN
    RAISE EXCEPTION 'Practice copy is invalid' USING ERRCODE = '22023';
  END IF;

  v_task_category := lower(p_category);

  INSERT INTO public.daily_formation_assignments (
    user_id, practice_date, practice_key, category, focus, practice_source,
    title, action, benefit, minutes, xp_reward, selection_reason
  ) VALUES (
    v_user_id, p_practice_date, p_practice_key, p_category, v_catalog.focus, 'reviewed',
    btrim(p_title), btrim(p_action), btrim(p_benefit), p_minutes, 10,
    left(btrim(COALESCE(NULLIF(p_selection_reason, ''), 'Prepared for today')), 160)
  )
  ON CONFLICT ON CONSTRAINT daily_formation_assignments_user_date_category_key DO NOTHING;

  SELECT assignment.* INTO v_assignment
  FROM public.daily_formation_assignments AS assignment
  WHERE assignment.user_id = v_user_id
    AND assignment.practice_date = p_practice_date
    AND assignment.category = p_category
  FOR UPDATE;

  IF v_assignment.task_id IS NULL THEN
    SELECT task.id INTO v_task_id
    FROM public.daily_tasks AS task
    WHERE task.user_id = v_user_id
      AND task.task_date = p_practice_date
      AND task.source = 'faithful_step'
      AND task.category = v_task_category
    ORDER BY task.created_at ASC NULLS LAST
    LIMIT 1;

    IF v_task_id IS NULL THEN
      INSERT INTO public.daily_tasks (
        user_id, task_text, difficulty, xp_reward, task_date, completed,
        is_main_quest, scheduled_time, reminder_enabled, category, notes,
        source, ai_generated
      ) VALUES (
        v_user_id, v_assignment.action, 'easy', 10, v_assignment.practice_date,
        false, true, NULL, false, v_task_category,
        v_assignment.title || ' · ' || v_assignment.benefit,
        'faithful_step', true
      ) RETURNING id INTO v_task_id;
    END IF;

    UPDATE public.daily_formation_assignments
    SET task_id = v_task_id
    WHERE id = v_assignment.id
    RETURNING * INTO v_assignment;
  END IF;

  INSERT INTO public.formation_progress (user_id)
  VALUES (v_user_id)
  ON CONFLICT (user_id) DO NOTHING;

  RETURN QUERY
  SELECT
    v_assignment.id, v_assignment.practice_date, v_assignment.practice_key,
    v_assignment.category, v_assignment.title, v_assignment.action,
    v_assignment.benefit, v_assignment.minutes, v_assignment.xp_reward,
    v_assignment.selection_reason, v_assignment.task_id, v_assignment.completed_at,
    progress.total_xp, progress.practices_completed
  FROM public.formation_progress AS progress
  WHERE progress.user_id = v_user_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.align_daily_formation_practice(
  p_assignment_id uuid,
  p_practice_key text,
  p_category text,
  p_title text,
  p_action text,
  p_benefit text,
  p_minutes integer,
  p_selection_reason text
)
RETURNS TABLE (
  assignment_id uuid,
  practice_date date,
  practice_key text,
  category text,
  title text,
  action text,
  benefit text,
  minutes integer,
  xp_reward integer,
  selection_reason text,
  task_id uuid,
  completed_at timestamptz,
  total_xp integer,
  practices_completed integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_user_id uuid := auth.uid();
  v_assignment public.daily_formation_assignments%ROWTYPE;
  v_catalog public.daily_formation_practice_catalog%ROWTYPE;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '42501';
  END IF;

  SELECT catalog.* INTO v_catalog
  FROM public.daily_formation_practice_catalog AS catalog
  WHERE catalog.practice_key = p_practice_key;

  IF NOT FOUND OR v_catalog.category <> p_category THEN
    RAISE EXCEPTION 'Formation practice does not belong to the requested category' USING ERRCODE = '22023';
  END IF;
  IF p_minutes IS NULL OR p_minutes NOT BETWEEN 1 AND 15 THEN
    RAISE EXCEPTION 'Practice duration is invalid' USING ERRCODE = '22023';
  END IF;
  IF length(btrim(COALESCE(p_title, ''))) NOT BETWEEN 1 AND 120
    OR length(btrim(COALESCE(p_action, ''))) NOT BETWEEN 1 AND 600
    OR length(btrim(COALESCE(p_benefit, ''))) NOT BETWEEN 1 AND 600 THEN
    RAISE EXCEPTION 'Practice copy is invalid' USING ERRCODE = '22023';
  END IF;

  SELECT assignment.* INTO v_assignment
  FROM public.daily_formation_assignments AS assignment
  WHERE assignment.id = p_assignment_id
    AND assignment.user_id = v_user_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Faithful Step not found' USING ERRCODE = 'P0002';
  END IF;
  IF v_assignment.category <> p_category THEN
    RAISE EXCEPTION 'Faithful Steps can only be aligned within their existing pillar' USING ERRCODE = '22023';
  END IF;

  IF v_assignment.completed_at IS NULL THEN
    UPDATE public.daily_formation_assignments AS assignment
    SET
      practice_key = p_practice_key,
      practice_source = 'reviewed',
      focus = v_catalog.focus,
      title = btrim(p_title),
      action = btrim(p_action),
      benefit = btrim(p_benefit),
      minutes = p_minutes,
      selection_reason = left(btrim(COALESCE(NULLIF(p_selection_reason, ''), 'Connected to today''s Guide reflection')), 160),
      scripture_reference = NULL,
      generation_model = NULL,
      generation_prompt_version = NULL,
      updated_at = now()
    WHERE assignment.id = v_assignment.id
    RETURNING assignment.* INTO v_assignment;

    IF v_assignment.task_id IS NOT NULL THEN
      UPDATE public.daily_tasks AS task
      SET
        task_text = v_assignment.action,
        category = lower(v_assignment.category),
        notes = v_assignment.title || ' · ' || v_assignment.benefit
      WHERE task.id = v_assignment.task_id
        AND task.user_id = v_user_id
        AND task.completed = false;
    END IF;
  END IF;

  INSERT INTO public.formation_progress (user_id)
  VALUES (v_user_id)
  ON CONFLICT (user_id) DO NOTHING;

  RETURN QUERY
  SELECT
    v_assignment.id, v_assignment.practice_date, v_assignment.practice_key,
    v_assignment.category, v_assignment.title, v_assignment.action,
    v_assignment.benefit, v_assignment.minutes, v_assignment.xp_reward,
    v_assignment.selection_reason, v_assignment.task_id, v_assignment.completed_at,
    progress.total_xp, progress.practices_completed
  FROM public.formation_progress AS progress
  WHERE progress.user_id = v_user_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.prepare_generated_daily_formation_practice(
  p_user_id uuid,
  p_practice_date date,
  p_practice_key text,
  p_category text,
  p_focus text,
  p_title text,
  p_action text,
  p_benefit text,
  p_minutes integer,
  p_selection_reason text,
  p_scripture_reference text,
  p_generation_model text,
  p_prompt_version text
)
RETURNS TABLE (
  assignment_id uuid,
  practice_date date,
  practice_key text,
  category text,
  focus text,
  practice_source text,
  title text,
  action text,
  benefit text,
  minutes integer,
  xp_reward integer,
  selection_reason text,
  scripture_reference text,
  generation_model text,
  generation_prompt_version text,
  task_id uuid,
  completed_at timestamptz,
  total_xp integer,
  practices_completed integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_assignment public.daily_formation_assignments%ROWTYPE;
  v_task_id uuid;
  v_task_category text;
BEGIN
  IF auth.role() IS DISTINCT FROM 'service_role' THEN
    RAISE EXCEPTION 'Service role required' USING ERRCODE = '42501';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = p_user_id) THEN
    RAISE EXCEPTION 'User not found' USING ERRCODE = 'P0002';
  END IF;
  IF p_practice_date IS NULL
    OR p_practice_date < current_date - 1
    OR p_practice_date > current_date + 1 THEN
    RAISE EXCEPTION 'Practice date must be the user''s current local day' USING ERRCODE = '22023';
  END IF;
  IF p_practice_key IS NULL OR p_practice_key !~ '^generated-[a-f0-9]{24}$' THEN
    RAISE EXCEPTION 'Generated practice key is invalid' USING ERRCODE = '22023';
  END IF;
  IF NOT (
    (p_category = 'Mind' AND p_focus = 'knowledge')
    OR (p_category = 'Body' AND p_focus IN ('exercise', 'nutrition'))
    OR (p_category = 'Soul' AND p_focus IN ('scripture', 'faith'))
  ) THEN
    RAISE EXCEPTION 'Generated practice focus is outside its pillar' USING ERRCODE = '22023';
  END IF;
  IF p_minutes IS NULL OR p_minutes NOT BETWEEN 2 AND 15 THEN
    RAISE EXCEPTION 'Practice duration is invalid' USING ERRCODE = '22023';
  END IF;
  IF length(btrim(COALESCE(p_title, ''))) NOT BETWEEN 3 AND 80
    OR length(btrim(COALESCE(p_action, ''))) NOT BETWEEN 20 AND 300
    OR length(btrim(COALESCE(p_benefit, ''))) NOT BETWEEN 20 AND 240
    OR length(btrim(COALESCE(p_generation_model, ''))) NOT BETWEEN 1 AND 80
    OR length(btrim(COALESCE(p_prompt_version, ''))) NOT BETWEEN 1 AND 80 THEN
    RAISE EXCEPTION 'Generated practice copy or metadata is invalid' USING ERRCODE = '22023';
  END IF;
  IF p_category <> 'Soul' AND p_scripture_reference IS NOT NULL THEN
    RAISE EXCEPTION 'Scripture references belong to the Soul pillar' USING ERRCODE = '22023';
  END IF;

  v_task_category := lower(p_category);

  INSERT INTO public.daily_formation_assignments (
    user_id, practice_date, practice_key, category, focus, practice_source,
    title, action, benefit, minutes, xp_reward, selection_reason,
    scripture_reference, generation_model, generation_prompt_version
  ) VALUES (
    p_user_id, p_practice_date, p_practice_key, p_category, p_focus, 'generated',
    btrim(p_title), btrim(p_action), btrim(p_benefit), p_minutes, 10,
    left(btrim(COALESCE(NULLIF(p_selection_reason, ''), 'Personalized for today')), 160),
    NULLIF(btrim(COALESCE(p_scripture_reference, '')), ''),
    btrim(p_generation_model), btrim(p_prompt_version)
  )
  ON CONFLICT ON CONSTRAINT daily_formation_assignments_user_date_category_key DO NOTHING;

  SELECT assignment.* INTO v_assignment
  FROM public.daily_formation_assignments AS assignment
  WHERE assignment.user_id = p_user_id
    AND assignment.practice_date = p_practice_date
    AND assignment.category = p_category
  FOR UPDATE;

  IF v_assignment.task_id IS NULL THEN
    SELECT task.id INTO v_task_id
    FROM public.daily_tasks AS task
    WHERE task.user_id = p_user_id
      AND task.task_date = p_practice_date
      AND task.source = 'faithful_step'
      AND task.category = v_task_category
    ORDER BY task.created_at ASC NULLS LAST
    LIMIT 1;

    IF v_task_id IS NULL THEN
      INSERT INTO public.daily_tasks (
        user_id, task_text, difficulty, xp_reward, task_date, completed,
        is_main_quest, scheduled_time, reminder_enabled, category, notes,
        source, ai_generated
      ) VALUES (
        p_user_id, v_assignment.action, 'easy', 10, v_assignment.practice_date,
        false, true, NULL, false, v_task_category,
        v_assignment.title || ' · ' || v_assignment.benefit,
        'faithful_step', true
      ) RETURNING id INTO v_task_id;
    END IF;

    UPDATE public.daily_formation_assignments
    SET task_id = v_task_id
    WHERE id = v_assignment.id
    RETURNING * INTO v_assignment;
  END IF;

  INSERT INTO public.formation_progress (user_id)
  VALUES (p_user_id)
  ON CONFLICT (user_id) DO NOTHING;

  RETURN QUERY
  SELECT
    v_assignment.id, v_assignment.practice_date, v_assignment.practice_key,
    v_assignment.category, v_assignment.focus, v_assignment.practice_source,
    v_assignment.title, v_assignment.action, v_assignment.benefit,
    v_assignment.minutes, v_assignment.xp_reward, v_assignment.selection_reason,
    v_assignment.scripture_reference, v_assignment.generation_model,
    v_assignment.generation_prompt_version, v_assignment.task_id,
    v_assignment.completed_at, progress.total_xp, progress.practices_completed
  FROM public.formation_progress AS progress
  WHERE progress.user_id = p_user_id;
END;
$function$;

REVOKE ALL ON TABLE public.daily_formation_practice_catalog FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.prepare_generated_daily_formation_practice(
  uuid, date, text, text, text, text, text, text, integer, text, text, text, text
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.prepare_generated_daily_formation_practice(
  uuid, date, text, text, text, text, text, text, integer, text, text, text, text
) TO service_role;

COMMENT ON TABLE public.daily_formation_practice_catalog IS
  'Category and focus allowlist for Graceward''s reviewed Mind, Body, and Soul practices.';
COMMENT ON TABLE public.daily_formation_assignments IS
  'One stable reviewed or validated generated Mind, Body, and Soul quest per Graceward user day.';
COMMENT ON FUNCTION public.prepare_generated_daily_formation_practice(
  uuid, date, text, text, text, text, text, text, integer, text, text, text, text
) IS 'Service-only persistence boundary for validated AI-generated formation practices.';

COMMIT;
