// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Capacitor } from '@capacitor/core';
import type { Database } from './types';
import { safeLocalStorage } from '@/utils/storage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate required environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing required environment variables: VITE_SUPABASE_URL and/or VITE_SUPABASE_PUBLISHABLE_KEY. ' +
    'Copy .env.example to .env.local and populate the Supabase values before starting the app.'
  );
}

// Create a safe storage adapter for Supabase (handles iOS/private browsing)
const supabaseStorage = {
  getItem: (key: string) => {
    return safeLocalStorage.getItem(key);
  },
  setItem: (key: string, value: string) => {
    safeLocalStorage.setItem(key, value);
  },
  removeItem: (key: string) => {
    safeLocalStorage.removeItem(key);
  },
};

const nativeAuthLock = async <Result>(
  _name: string,
  _acquireTimeout: number,
  callback: () => Promise<Result>,
): Promise<Result> => callback();

const authLock = Capacitor.isNativePlatform() ? nativeAuthLock : undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: supabaseStorage,
    persistSession: true,
    autoRefreshToken: true,
    lock: authLock,
  }
});
