// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { safeLocalStorage } from '@/utils/storage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Create a safe storage adapter for Supabase (handles iOS/private browsing)
const supabaseStorage = {
  getItem: (key: string) => {
    return safeLocalStorage.getItem(key);
  },
  setItem: (key: string, value: string) => {
    safeLocalStorage.setItem(key, value);
  },
  removeItem: (key: string) => {
    safeLocalStorage.removeItem(key);
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create Supabase client only if env vars are present (migrating to Firebase)
// Otherwise create a mock client that won't crash but will log warnings
let supabase: ReturnType<typeof createClient<Database>>;

if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: supabaseStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
} else {
  // Mock client for migration period - prevents crashes but logs warnings
  console.warn('⚠️ Supabase client not initialized - migrating to Firebase. Some features may not work.');
  supabase = createClient<Database>('https://placeholder.supabase.co', 'placeholder-key', {
    auth: {
      storage: supabaseStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

export { supabase };