// This file is automatically generated. Do not edit it directly.
import { createClient, processLock } from '@supabase/supabase-js';
import { Capacitor } from '@capacitor/core';
import type { Database } from './types';
import { authSessionStorage } from '@/utils/authSessionStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const COSMIQ_SUPABASE_PROJECT_REF = 'opbfpbbqvuksuvmtmssd';
const EXPECTED_SUPABASE_PROJECT_REF =
  import.meta.env.VITE_EXPECTED_SUPABASE_PROJECT_REF?.trim();

const getSupabaseProjectRef = (url: string): string => {
  try {
    return new URL(url).hostname.split('.')[0] || 'project';
  } catch {
    return 'project';
  }
};

const projectRef = getSupabaseProjectRef(SUPABASE_URL ?? '');

// Validate required environment variables
if (
  !SUPABASE_URL ||
  !SUPABASE_PUBLISHABLE_KEY ||
  !EXPECTED_SUPABASE_PROJECT_REF
) {
  throw new Error(
    'Missing required environment variables: VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY, ' +
    'and/or VITE_EXPECTED_SUPABASE_PROJECT_REF. ' +
    'Copy .env.example to .env.local and populate the Supabase values before starting the app.'
  );
}

if (EXPECTED_SUPABASE_PROJECT_REF !== COSMIQ_SUPABASE_PROJECT_REF) {
  throw new Error(
    `Blocked Cosmiq startup: the configured expected Supabase project must be ` +
    `${COSMIQ_SUPABASE_PROJECT_REF}.`,
  );
}

if (projectRef !== COSMIQ_SUPABASE_PROJECT_REF) {
  throw new Error(
    `Blocked Cosmiq startup: Supabase project ${projectRef} does not match ` +
    `the dedicated Cosmiq project ${COSMIQ_SUPABASE_PROJECT_REF}.`,
  );
}


// Serialize refresh-token rotation within the native WebView without relying
// on Web Locks (which can remain suspended when iOS backgrounds the app).
const authLock = Capacitor.isNativePlatform() ? processLock : undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: authSessionStorage,
    persistSession: true,
    autoRefreshToken: true,
    lock: authLock,
  }
});
